---
name: gdsfactory
channels:
    - conda-forge
dependencies:
    - python
    - nbgitpuller
    - ffmpeg
    - numpy
    - scipy
    - pymeep
    - pip
    - pip:
          - nlopt
          - matplotlib
          - autograd
          - jax
