[tool.poetry]
name = "gdsfactory"
version = "5.6.7"
description = "library for GDS layouts"
authors = ["gdsfactory community"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7"
click = "^8.0.3"
gdspy = "^1.6.11"
jsondiff = "^1.3.0"
loguru = "^0.5.3"
lytest = "^0.0.20"
matplotlib = "^3.5.1"
networkx = "^2.6.3"
omegaconf = "^2.1.1"
phidl = "^1.6.1"
picwriter = "^0.5"
pydantic = "^1.8.2"
Pyqtree = "^1.0.0"
pytest = "^6.2.5"
pytest-regressions = "^2.2.0"
qrcode = "^7.3.1"
rectpack = "^0.2.2"
scikit-image = "^0.19.1"
semantic-version = "^2.8.5"
Shapely = "^1.8.0"
toolz = "^0.11.2"
trimesh = "^3.9.36"
typing-extensions = "^4.0.1"
xmltodict = "^0.12.0"
klayout = "^0.27.1"
flatdict  = "^4.0.1"
tqdm = "^4.63.0"
orjson = "^3.6.7"

[tool.poetry.dev-dependencies]
doc8 = {version = "^0.10.1", optional = true}
docutils = {version = "^0.18.1", optional = true}
flake8 = {version = "^4.0.1", optional = true}
flake8-rst-docstrings = {version = "^0.2.5", optional = true}
ipykernel = {version = "^6.6.0", optional = true}
mypy = {version = "^0.920", optional = true}
nbsphinx = {version = "^0.8.7", optional = true}
nbval = {version = "^0.9.6", optional = true}
pre-commit = {version = "^2.16.0", optional = true}
pydocstyle = {version = "^6.1.1", optional = true}
pyglet = {version = "^1.5.21", optional = true}
pytest-cov = {version = "^3.0.0", optional = true}
recommonmark = {version = "^0.7.1", optional = true}
sphinx-autodoc-typehints = {version = "^1.12.0", optional = true}
sphinx-click = {version = "^3.0.2", optional = true}
sphinx-markdown-tables = "^0.0.15"
ipympl = "^0.8.7"
holoviews = "^1.14.7"
xdoctest = "^0.15.10"
tox = "^3.24.4"

[tool.poetry.extras]
full = ['holoviews', 'ipympl', 'tidy3d', 'triangle']
dash = ['dash',"dash-bootstrap-components>=0.8.2", "Werkzeug==2.0.0"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gf = "gdsfactory.gf:gf"
