info:
  dy: 10.0
  length: 16.637
  min_bend_radius: 7.061
  radius: 10.0
  route_info_length: 16.637
  route_info_min_bend_radius: 7.061
  route_info_n_bend_90: 1.0
  route_info_strip_length: 16.637
  route_info_type: strip
  route_info_weight: 16.637
  width: 0.5
name: bend_euler_RNone_A90_P0_d7c3a5a9
settings:
  allow_min_radius_violation: 0
  angle: 90.0
  cross_section: strip
  p: 0.5
  with_arc_floorplan: 1
