function: spiral_racetrack_heater_doped
info: {}
module: gdsfactory.components.spiral_heater
name: spiral_racetrack_heater_doped
settings:
  bend_factory:
    function: bend_euler
  bend_s_factory:
    function: bend_s
  heater_cross_section: xs_npp
  num: 8
  spacing: 2
  straight_factory:
    function: straight
  straight_length: 30
  waveguide_cross_section: xs_sc
