name: spiral_inner_io_length20000p0_add_grating_couplers_with_loopback_fiber_array
ports:
  loopback_1:
    center:
      - -127.0
      - 46.0
    layer:
      - 1
      - 0
    name: loopback_1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  loopback_4:
    center:
      - -127.0
      - 46.0
    layer:
      - 1
      - 0
    name: loopback_4
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o1:
    center:
      - 0.0
      - 50.0
    layer:
      - 1
      - 0
    name: o1
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
      - 127.0
      - 50.0
    layer:
      - 1
      - 0
    name: o2
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child:
    changed:
      length: 20000.0
    child: null
    default:
      N: 6
      asymmetric_cross_section: false
      bend180:
        function: bend_euler
        settings:
          angle: 180
      bend90:
        function: bend_euler
      cross_section: strip
      cross_section_bend: null
      cross_section_bend180: null
      grating_spacing: 127.0
      length: null
      straight:
        function: straight
      waveguide_spacing: 3.0
      x_straight_inner_left: 50.0
      x_straight_inner_right: 150.0
      y_straight_inner_bottom: 10.0
      y_straight_inner_top: 50.0
    full:
      N: 6
      asymmetric_cross_section: false
      bend180:
        function: bend_euler
        settings:
          angle: 180
      bend90:
        function: bend_euler
      cross_section: strip
      cross_section_bend: null
      cross_section_bend180: null
      grating_spacing: 127.0
      length: 20000.0
      straight:
        function: straight
      waveguide_spacing: 3.0
      x_straight_inner_left: 50.0
      x_straight_inner_right: 150.0
      y_straight_inner_bottom: 10.0
      y_straight_inner_top: 50.0
    function_name: spiral_inner_io
    info:
      length: 19999.999
    info_version: 2
    module: gdsfactory.components.spiral_inner_io
    name: spiral_inner_io_length20000p0
  default:
    bend:
      function: bend_euler
    component:
      component: spiral_inner_io
      settings:
        length: 20000.0
    component_name: null
    cross_section: strip
    excluded_ports: null
    gc_port_name: o1
    gc_rotation: -90
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    grating_separation: 127.0
    layer_label: null
    layer_label_loopback: null
    loopback_yspacing: 4.0
    nlabels_loopback: 2
    select_ports:
      function: select_ports
      settings:
        port_type: optical
    straight_separation: 5.0
    with_loopback: true
  full:
    bend:
      function: bend_euler
    component:
      component: spiral_inner_io
      settings:
        length: 20000.0
    component_name: null
    cross_section: strip
    excluded_ports: null
    gc_port_name: o1
    gc_rotation: -90
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    grating_separation: 127.0
    layer_label: null
    layer_label_loopback: null
    loopback_yspacing: 4.0
    nlabels_loopback: 2
    select_ports:
      function: select_ports
      settings:
        port_type: optical
    straight_separation: 5.0
    with_loopback: true
  function_name: add_grating_couplers_with_loopback_fiber_array
  info:
    length: 19999.999
    polarization: te
    wavelength: 1.53
  info_version: 2
  module: gdsfactory.components.add_grating_couplers
  name: spiral_inner_io_length20000p0_add_grating_couplers_with_loopback_fiber_array
