name: cdsem_coupler
ports: {}
settings:
  cross_section: xs_sc
  gaps:
  - 0.15
  - 0.2
  - 0.25
  length: 420.0
  positions: null
  spacing: 7.0
  text:
    function: text_rectangular
    settings:
      size: 1
