function: litho_steps
info: {}
module: gdsfactory.components.litho_steps
name: litho_steps
settings:
  height: 100.0
  layer: WG
  line_spacing: 10.0
  line_widths:
  - 1.0
  - 2.0
  - 4.0
  - 8.0
  - 16.0
