name: coupler_asymmetric
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 1.234
  o2:
    center:
    - 10.0
    - 0.367
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 10.0
    - -2.133
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bend:
    function: bend_s
  cross_section: xs_sc_no_pins
  dx: 10.0
  dy: 2.5
  gap: 0.234
