info:
  polarization: te
  wavelength: 1.554
name: grating_coupler_ellipti_961359c2
settings:
  bias_gap: 0
  cross_section: strip
  fiber_angle: 15
  fill_factor: 0.5
  gaps:
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  layer_slab: SLAB150
  n_periods: 20
  nclad: 1.443
  period: 0.75
  polarization: te
  spiked: true
  taper_angle: 60
  taper_length: 16.6
  taper_to_slab_offset: -3
  wavelength: 1.554
  widths:
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
  - 0.375
