info: {}
name: straight_heater_meander_dc738148
settings:
  cross_section: strip
  extension_length: 15.0
  heater_width: 1.5
  layers_doping:
  - P
  - PP
  - PPP
  length: 300.0
  radius: 5.0
  spacing: 2.0
  straight_widths:
  - 0.8
  - 0.9
  - 0.8
  taper_length: 10
  via_stack: Fvia_stack_Mgdsfactorypcomponentspviaspvia_stack_SS1p5_1p5_LM1_M2_VFvia_Mgdsfactorypcomponentspviaspvia_SLVIAC_S0p1_0p1_S0p2_0p2_E0p1_Fvia_Mgdsfactorypcomponentspviaspvia_SLVIA1_S0p1_0p1_S0p2_0p2_E0p1
