info:
  dy: 0
  length: 42.817
  min_bend_radius: 9.086
  radius: 10
  route_info_length: 42.817
  route_info_min_bend_radius: 9.086
  route_info_n_bend_90: 2
  route_info_type: xs_34e31a19
  route_info_weight: 42.817
  route_info_xs_34e31a19_length: 42.817
name: bend_euler_RNone_A180_P_a75aec30
settings:
  allow_min_radius_violation: false
  angle: 180
  cross_section: strip
  p: 0.5
  with_arc_floorplan: true
