name: text_rectangular
ports: {}
settings:
  changed: {}
  child: null
  default:
    font:
      function: rectangular_font
    justify: left
    layer: WG
    position:
    - 0.0
    - 0.0
    size: 10.0
    text: abcd
  full:
    font:
      function: rectangular_font
    justify: left
    layer: WG
    position:
    - 0.0
    - 0.0
    size: 10.0
    text: abcd
  function_name: text_rectangular
  info: {}
  info_version: 2
  module: gdsfactory.components.text_rectangular
  name: text_rectangular
