function: fanout2x2
info: {}
module: gdsfactory.routing.fanout2x2
name: mzi_fanout2x2_componentmzi_2e88f57c
settings:
  bend_length: null
  component:
    function: mzi
    module: gdsfactory.components.mzi
    settings:
      add_electrical_ports_bot: true
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: xs_sc
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      extend_ports_straight_x: null
      info: null
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      post_process: null
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
  cross_section: xs_sc
  npoints: 101
  port_spacing: 20.0
  select_ports:
    function: select_ports
    module: gdsfactory.port
    settings:
      port_type: optical
