name: straight_heater_metal_undercut_with_undercutFalse_bend_port
ports:
  l_e1:
    center:
      - 324.9
      - -20.0
    layer:
      - 49
      - 0
    name: l_e1
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  l_e2:
    center:
      - -10.4
      - 5.5
    layer:
      - 49
      - 0
    name: l_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e3:
    center:
      - -4.9
      - 0.0
    layer:
      - 49
      - 0
    name: l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  l_e4:
    center:
      - -10.4
      - -5.5
    layer:
      - 49
      - 0
    name: l_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  o1:
    center:
      - 0.0
      - 0.0
    layer:
      - 1
      - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
      - 320.0
      - 0.0
    layer:
      - 1
      - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  r_e1:
    center:
      - 324.9
      - 0.0
    layer:
      - 49
      - 0
    name: r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e2:
    center:
      - 330.4
      - 5.5
    layer:
      - 49
      - 0
    name: r_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e3:
    center:
      - 335.9
      - 0.0
    layer:
      - 49
      - 0
    name: r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  r_e4:
    center:
      - 330.4
      - -5.5
    layer:
      - 49
      - 0
    name: r_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  changed: {}
  child: null
  default:
    angle: 180
    bend:
      function: bend_circular
    component:
      function: straight_heater_metal_undercut
      settings:
        with_undercut: false
    cross_section: metal3
    extension_length: null
    port_name: l_e1
    port_name1_bend: null
    port_name2: r_e1
    port_name2_bend: null
  full:
    angle: 180
    bend:
      function: bend_circular
    component:
      function: straight_heater_metal_undercut
      settings:
        with_undercut: false
    cross_section: metal3
    extension_length: null
    port_name: l_e1
    port_name1_bend: null
    port_name2: r_e1
    port_name2_bend: null
  function_name: bend_port
  info:
    resistance: null
  info_version: 2
  module: gdsfactory.components.bend_port
  name: straight_heater_metal_undercut_with_undercutFalse_bend_port
