info:
  dy: 0
  length: 31.415
  radius: 10
  route_info_length: 31.415
  route_info_min_bend_radius: 10
  route_info_n_bend_90: 2
  route_info_strip_length: 31.415
  route_info_type: strip
  route_info_weight: 31.415
  width: 0.5
name: bend_circular_RNone_A18_72bb12de
settings:
  allow_min_radius_violation: false
  angle: 180
  cross_section: strip
