name: mzi_2e88f57c_add_electrical_pads_shortest_564dd830
ports:
  elec-mzi_2e88f57c-1:
    center:
    - 19.5
    - 122.625
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-1
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-2:
    center:
    - 76.6
    - 122.625
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-2
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-3:
    center:
    - 25.0
    - 128.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-3
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-4:
    center:
    - 82.1
    - 128.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-4
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-5:
    center:
    - 30.5
    - 122.625
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-5
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-6:
    center:
    - 87.6
    - 122.625
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-6
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-7:
    center:
    - 82.1
    - 117.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-7
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-8:
    center:
    - 25.0
    - 117.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-8
    orientation: null
    port_type: vertical_dc
    shear_angle: null
    width: 100.0
  o1:
    center:
    - -10.0
    - -0.625
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - -10.0
    - 0.625
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 117.12
    - 0.625
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 117.12
    - -0.625
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    component:
      component: mzi
      settings:
        combiner:
          function: mmi2x2
        port_e0_combiner: o4
        port_e0_splitter: o4
        port_e1_combiner: o3
        port_e1_splitter: o3
        splitter:
          function: mmi2x2
        straight_x_top: straight_heater_metal
  child:
    changed:
      combiner:
        function: mmi2x2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight_x_top: straight_heater_metal
    child: null
    default:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner: null
      cross_section: strip
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o3
      port_e0_splitter: o3
      port_e1_combiner: o2
      port_e1_splitter: o2
      splitter: mmi1x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: null
      straight_y: null
      with_splitter: true
    full:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: strip
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
    function_name: mzi
    info: {}
    info_version: 2
    module: gdsfactory.components.mzi
    name: mzi_2e88f57c
  default:
    component:
      function: straight
    layer: M3
    pad: pad
    pad_port_spacing: 50.0
    port_names: null
    port_orientation: 90
    select_ports:
      function: select_ports
      settings:
        port_type: electrical
  full:
    component:
      component: mzi
      settings:
        combiner:
          function: mmi2x2
        port_e0_combiner: o4
        port_e0_splitter: o4
        port_e1_combiner: o3
        port_e1_splitter: o3
        splitter:
          function: mmi2x2
        straight_x_top: straight_heater_metal
    layer: M3
    pad: pad
    pad_port_spacing: 50.0
    port_names: null
    port_orientation: 90
    select_ports:
      function: select_ports
      settings:
        port_type: electrical
  function_name: add_electrical_pads_shortest
  info: {}
  info_version: 2
  module: gdsfactory.routing.add_electrical_pads_shortest
  name: mzi_2e88f57c_add_electrical_pads_shortest_564dd830
