function_name: add_frame
info: {}
module: gdsfactory.components.align
name: add_frame
ports: {}
settings:
  component:
    function: rectangle
  layer: WG
  layers: null
  spacing: 10.0
  width: 10.0
