name: bend_circular
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 10.0
    - 10.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    add_bbox: null
    add_pins: true
    angle: 90.0
    cross_section: xs_sc
    layer: null
    npoints: null
    radius: null
    width: null
  full:
    add_bbox: null
    add_pins: true
    angle: 90.0
    cross_section: xs_sc
    layer: null
    npoints: null
    radius: null
    width: null
  function_name: bend_circular
  info:
    dy: 10.0
    length: 15.708
    radius: 10.0
    route_info:
      length: 15.708
      n_bend_90: 1.0
      type: xs_sc
      weight: 15.708
      xs_sc_length: 15.708
  info_version: 2
  module: gdsfactory.components.bend_circular
  name: bend_circular
