function: via_stack
info:
  layer: MTOP
  size:
  - 11.0
  - 11.0
  xsize: 11.0
  ysize: 11.0
module: gdsfactory.components.via_stack
name: via_stack_a292abbc
settings:
  correct_size: true
  layer_offsets: null
  layer_port: null
  layers:
  - SLAB90
  - M1
  - M2
  - MTOP
  post_process: null
  size:
  - 11.0
  - 11.0
  slot_horizontal: false
  slot_vertical: false
  vias:
  - function: via
    module: gdsfactory.components.via
    settings:
      layer: VIAC
  - function: via
    module: gdsfactory.components.via
    settings:
      enclosure: 2
      layer: VIA1
  - function: via
    module: gdsfactory.components.via
    settings:
      layer: VIA2
  - null
