function: grating_coupler_elliptical_lumerical
info:
  polarization: te
  wavelength: 1.554
module: gdsfactory.components.grating_coupler_elliptical_lumerical
name: grating_coupler_elliptical_lumerical
settings:
  bias_gap: 0
  fiber_angle: 5
  info: null
  layer: WG
  layer_slab: SLAB150
  parameters:
  - -2.429836
  - 0.1
  - 0.48007
  - 0.1
  - 0.607398
  - 0.1
  - 0.449884
  - 0.1
  - 0.427412
  - 0.1
  - 0.47579
  - 0.1
  - 0.502665
  - 0.100029
  - 0.510037
  - 0.1
  - 0.4944
  - 0.10796
  - 0.474006
  - 0.149727
  - 0.432728
  - 0.183953
  - 0.387202
  - 0.236018
  - 0.360322
  - 0.242618
  - 0.357704
  - 0.260664
  - 0.35261
  - 0.246682
  - 0.371749
  - 0.229208
  - 0.377696
  - 0.224653
  - 0.376544
  - 0.220418
  - 0.380476
  - 0.219236
  - 0.379887
  - 0.217004
  - 0.382917
  - 0.218278
  - 0.364132
  - 0.237291
  - 0.367683
  - 0.248651
  - 0.344151
  - 0.273357
  - 0.330623
  - 0.273504
  taper_angle: 55
  taper_length: 12.6
