name: ring_double_add_trenches_e76d6c77
ports:
  o1:
    center:
    - -13.01
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 13.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - -13.01
    - 21.41
    layer:
    - 1
    - 0
    name: o3
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 13.0
    - 21.41
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    component:
      function: ring_double
  child: null
  default:
    bot: true
    component:
      function: coupler
    cross_section: xs_rc_with_trenches
    left: false
    right: false
    top: true
  full:
    bot: true
    component:
      function: ring_double
    cross_section: xs_rc_with_trenches
    left: false
    right: false
    top: true
  function_name: add_trenches
  info: {}
  info_version: 2
  module: gdsfactory.components.add_trenches
  name: ring_double_add_trenches_e76d6c77
