info:
  end_angle: 0.0
  length: 11.206
  min_bend_radius: 13.012
  route_info_length: 11.206
  route_info_min_bend_radius: 13.012
  route_info_n_bend_s: 1
  route_info_strip_length: 11.206
  route_info_type: strip
  route_info_weight: 11.206
  start_angle: 0.0
name: bend_s_S11_1p8_N99_CSst_71d8cbbd
settings:
  allow_min_radius_violation: false
  cross_section: strip
  npoints: 99
  size:
  - 11.0
  - 1.8
