info: {}
name: die_S10000_10000_SW100__48b1c773
settings:
  bbox_layer: FLOORPLAN
  die_name: chip99
  draw_corners: false
  layer: FLOORPLAN
  size:
    - 10000
    - 10000
  street_length: 1000
  street_width: 100
  text: text
  text_location: SW
  text_size: 100
