function: ring_crow_couplers
info: {}
module: gdsfactory.components.ring_crow_couplers
name: ring_crow_couplers
settings:
  bends:
  - function: bend_circular
  - function: bend_circular
  - function: bend_circular
  couplers:
  - function: coupler_full
  - function: coupler_full
  - function: coupler_full
  - function: coupler_full
  radius:
  - 10.0
  - 10.0
  - 10.0
  ring_cross_sections:
  - function: cross_section
    module: gdsfactory.cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
  - function: cross_section
    module: gdsfactory.cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
  - function: cross_section
    module: gdsfactory.cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
