info: {}
name: litho_ruler_H2_W0p5_S2__a485f750
settings:
  height: 2
  layer: WG
  num_marks: 21
  scale:
    - 3
    - 1
    - 1
    - 1
    - 1
    - 2
    - 1
    - 1
    - 1
    - 1
  spacing: 2
  width: 0.5
