function: bend_s
info:
  end_angle: 0
  length: 11.206
  min_bend_radius: 13.012
  start_angle: 0
module: gdsfactory.components.bend_s
name: bend_s
settings:
  add_pins: true
  cross_section: xs_sc
  npoints: 99
  size:
  - 11.0
  - 1.8
  with_bbox: true
