info:
  length: 10.0
  route_info_length: 10.0
  route_info_metal_routing_length: 10.0
  route_info_type: metal_routing
  route_info_weight: 10.0
  width: 10.0
name: wire_straight_L10_N2_CS_ffb2e64f
settings:
  cross_section: metal_routing
  length: 10
  npoints: 2
