info:
  polarization: tm
  wavelength: 1.554
name: grating_coupler_ellipti_68e2db8b
settings:
  big_last_tooth: false
  cross_section: strip
  fiber_angle: 15
  grating_line_width: 0.707
  layer_slab: SLAB150
  n_periods: 16
  nclad: 1.443
  neff: 1.8
  polarization: tm
  slab_offset: 2
  slab_xmin: -2
  spiked: true
  taper_angle: 40
  taper_length: 30
  wavelength: 1.554
