info: {}
name: ring_single_bend_couple_154f7992
settings:
  bend: bend_circular
  bend_all_angle: bend_circular_all_angle
  bend_output: bend_euler
  coupling_angle_coverage: 180.0
  cross_section_inner: strip
  cross_section_outer: strip
  gap: 0.2
  length_x: 0.6
  length_y: 0.6
  radius: 5.0
