function_name: text_rectangular
info: {}
module: gdsfactory.components.text_rectangular
name: text_rectangular
ports: {}
settings:
  font:
    function: rectangular_font
  justify: left
  layer: WG
  layers: null
  position:
  - 0.0
  - 0.0
  size: 10.0
  text: abcd
