function: _from_yaml
info: {}
module: gdsfactory.read.from_yaml
name: sample_path_length_matching_215cd1fb
settings:
  conf:
    instances:
      bl:
        component: pad
      br:
        component: pad
      tl:
        component: pad
      tr:
        component: pad
    name: sample_path_length_matching
    placements:
      br:
        x: 900
        y: 400
      tl:
        x: 0
        y: 200
      tr:
        x: 900
        y: 600
    routes:
      route1:
        links:
          bl,e3: br,e1
          tl,e3: tr,e1
  label_instance_function:
    function: add_instance_label
  mode: layout
  routing_strategy:
    get_bundle:
      function: get_bundle
    get_bundle_all_angle:
      function: get_bundle_all_angle
    get_bundle_electrical:
      function: get_bundle
      module: gdsfactory.routing.get_bundle
      settings:
        bend:
          function: wire_corner
        cross_section: xs_metal_routing
    get_bundle_from_steps:
      function: get_bundle_from_steps
    get_bundle_from_steps_electrical:
      function: get_bundle_from_steps
      module: gdsfactory.routing.get_bundle_from_steps
      settings:
        bend:
          function: wire_corner
        cross_section: xs_metal_routing
    get_bundle_from_waypoints:
      function: get_bundle_from_waypoints
    get_bundle_path_length_match:
      function: get_bundle_path_length_match
    get_bundle_same_axis_no_grouping:
      function: get_bundle_same_axis_no_grouping
  validate: false
