name: coh_tx_single_pol
ports:
  mzm_i_top_bot_e1:
    center:
    - 45.5
    - 16.625
    layer:
    - 49
    - 0
    name: mzm_i_top_bot_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  mzm_i_top_bot_e2:
    center:
    - 135.5
    - 21.625
    layer:
    - 49
    - 0
    name: mzm_i_top_bot_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 180.0
  mzm_i_top_bot_e3:
    center:
    - 225.5
    - 16.625
    layer:
    - 49
    - 0
    name: mzm_i_top_bot_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  mzm_i_top_bot_e4:
    center:
    - 135.5
    - 11.625
    layer:
    - 49
    - 0
    name: mzm_i_top_bot_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 180.0
  mzm_i_top_top_e1:
    center:
    - 45.5
    - 28.625
    layer:
    - 49
    - 0
    name: mzm_i_top_top_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  mzm_i_top_top_e2:
    center:
    - 135.5
    - 33.625
    layer:
    - 49
    - 0
    name: mzm_i_top_top_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 180.0
  mzm_i_top_top_e3:
    center:
    - 225.5
    - 28.625
    layer:
    - 49
    - 0
    name: mzm_i_top_top_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  mzm_i_top_top_e4:
    center:
    - 135.5
    - 23.625
    layer:
    - 49
    - 0
    name: mzm_i_top_top_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 180.0
  mzm_q_top_bot_e1:
    center:
    - 45.5
    - -94.875
    layer:
    - 49
    - 0
    name: mzm_q_top_bot_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  mzm_q_top_bot_e2:
    center:
    - 135.5
    - -89.875
    layer:
    - 49
    - 0
    name: mzm_q_top_bot_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 180.0
  mzm_q_top_bot_e3:
    center:
    - 225.5
    - -94.875
    layer:
    - 49
    - 0
    name: mzm_q_top_bot_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  mzm_q_top_bot_e4:
    center:
    - 135.5
    - -99.875
    layer:
    - 49
    - 0
    name: mzm_q_top_bot_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 180.0
  mzm_q_top_top_e1:
    center:
    - 45.5
    - -82.875
    layer:
    - 49
    - 0
    name: mzm_q_top_top_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  mzm_q_top_top_e2:
    center:
    - 135.5
    - -77.875
    layer:
    - 49
    - 0
    name: mzm_q_top_top_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 180.0
  mzm_q_top_top_e3:
    center:
    - 225.5
    - -82.875
    layer:
    - 49
    - 0
    name: mzm_q_top_top_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  mzm_q_top_top_e4:
    center:
    - 135.5
    - -87.875
    layer:
    - 49
    - 0
    name: mzm_q_top_top_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 180.0
  o1:
    center:
    - -62.75
    - -55.75
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 473.77
    - -55.75
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  ps_q_bot_e1:
    center:
    - 331.02
    - -117.5
    layer:
    - 49
    - 0
    name: ps_q_bot_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  ps_q_bot_e2:
    center:
    - 371.02
    - -112.5
    layer:
    - 49
    - 0
    name: ps_q_bot_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  ps_q_bot_e3:
    center:
    - 411.02
    - -117.5
    layer:
    - 49
    - 0
    name: ps_q_bot_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  ps_q_bot_e4:
    center:
    - 371.02
    - -122.5
    layer:
    - 49
    - 0
    name: ps_q_bot_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  ps_q_top_e1:
    center:
    - 331.02
    - -105.5
    layer:
    - 49
    - 0
    name: ps_q_top_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  ps_q_top_e2:
    center:
    - 371.02
    - -100.5
    layer:
    - 49
    - 0
    name: ps_q_top_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 80.0
  ps_q_top_e3:
    center:
    - 411.02
    - -105.5
    layer:
    - 49
    - 0
    name: ps_q_top_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  ps_q_top_e4:
    center:
    - 371.02
    - -110.5
    layer:
    - 49
    - 0
    name: ps_q_top_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 80.0
settings:
  changed: {}
  child: null
  default:
    balanced_phase_shifters: false
    combiner: null
    cross_section: strip
    input_coupler: null
    mzm:
      component: mzi
      settings:
        cross_section_x_top: pin
        delta_length: 10.0
        straight_x_top: straight_pin
    mzm_length: 200.0
    mzm_ps_spacing: 40.0
    mzm_y_spacing: 50.0
    output_coupler: null
    pad_array: pad_array
    phase_shifter: straight_pin
    phase_shifter_length: 100.0
    splitter: mmi1x2
    with_pads: false
    xspacing: 40.0
  full:
    balanced_phase_shifters: false
    combiner: null
    cross_section: strip
    input_coupler: null
    mzm:
      component: mzi
      settings:
        cross_section_x_top: pin
        delta_length: 10.0
        straight_x_top: straight_pin
    mzm_length: 200.0
    mzm_ps_spacing: 40.0
    mzm_y_spacing: 50.0
    output_coupler: null
    pad_array: pad_array
    phase_shifter: straight_pin
    phase_shifter_length: 100.0
    splitter: mmi1x2
    with_pads: false
    xspacing: 40.0
  function_name: coh_tx_single_pol
  info: {}
  info_version: 2
  module: gdsfactory.components.coh_tx_single_pol
  name: coh_tx_single_pol
