name: mzi
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 81.12
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    add_optical_ports_arms: false
    bend:
      function: bend_euler
    combiner: null
    cross_section: strip
    cross_section_x_bot: null
    cross_section_x_top: null
    delta_length: 10.0
    length_x: 0.1
    length_y: 2.0
    mirror_bot: false
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter: mmi1x2
    straight:
      function: straight
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  full:
    add_optical_ports_arms: false
    bend:
      function: bend_euler
    combiner: null
    cross_section: strip
    cross_section_x_bot: null
    cross_section_x_top: null
    delta_length: 10.0
    length_x: 0.1
    length_y: 2.0
    mirror_bot: false
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter: mmi1x2
    straight:
      function: straight
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  function_name: mzi
  info: {}
  info_version: 2
  module: gdsfactory.components.mzi
  name: mzi
