name: fiber
ports:
  F0:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: F0
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 10
settings:
  cladding_diameter: 125
  core_diameter: 10
  layer_cladding: WGCLAD
  layer_core: WG
