name: bend_circular_angle180
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 0.0
    - 20.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    angle: 180
  child: null
  default:
    add_pins: true
    angle: 90.0
    cross_section: xs_sc
    layer: null
    npoints: null
    radius: null
    width: null
  full:
    add_pins: true
    angle: 180
    cross_section: xs_sc
    layer: null
    npoints: null
    radius: null
    width: null
  function_name: bend_circular
  info:
    dy: 0.0
    length: 31.415
    radius: 10.0
  info_version: 2
  module: gdsfactory.components.bend_circular
  name: bend_circular_angle180
