info: {}
name: ring_double_bend_couple_88df4a46
settings:
  bend: bend_circular_all_angle
  coupling_angle_coverage: 70.0
  cross_section_inner: strip
  cross_section_outer: strip
  gap: 0.2
  length_x: 0.6
  length_y: 0.6
  radius: 5.0
