function_name: die_bbox
info:
  area: 3380000
module: gdsfactory.components.die_bbox
name: rectangle_die_bbox
ports: {}
settings:
  component:
    function: rectangle
    module: gdsfactory.components.rectangle
    settings:
      size:
      - 1300
      - 2600
  die_name: null
  layer: MTOP
  padding: 10.0
  street_length: null
  street_width: 100.0
  text_anchor: sw
  text_size: 100.0
