info: {}
name: grating_coupler_array_G_b26a424e
settings:
  centered: true
  cross_section: strip
  grating_coupler: grating_coupler_elliptical
  n: 6
  pitch: 127.0
  port_name: o1
  rotation: -90
  straight_to_grating_spacing: 10.0
  with_loopback: false
