info: {}
name: cdsem_bend180_W0p5_R10__81075259
settings:
  bend90: bend_circular
  cross_section: strip
  radius: 10
  straight: straight
  text: Ftext_rectangular_Mgdsfactorypcomponentsptext_rectangular_SS1
  wg_length: 420
  width: 0.5
