function: array
info:
  layer:
  - 49
  - 0
  size:
  - 100.0
  - 100.0
  xsize: 100.0
  ysize: 100.0
module: gdsfactory.components.array_component
name: pad_array$1
settings:
  add_ports: true
  centered: false
  columns: 6
  component: pad
  rows: 1
  spacing:
  - 150.0
  - 150.0
