info: {}
name: greek_cross_L30_LWG_N_W_90adb163
settings:
  layers:
  - WG
  - N
  length: 30
  via_stack: Fvia_stack_Mgdsfactorypcomponentspvia_stack_SLWG_NPP_M1_VNone_None_Fvia_Mgdsfactorypcomponentspvia_SLVIAC
  widths:
  - 2
  - 3
