function: grating_coupler_elliptical
info:
  polarization: tm
  wavelength: 1.554
module: gdsfactory.components.grating_coupler_elliptical
name: grating_coupler_elliptical_def98097
settings:
  big_last_tooth: false
  cross_section: xs_sc
  fiber_angle: 15.0
  grating_line_width: 0.707
  info: null
  layer_slab: SLAB150
  n_periods: 16
  nclad: 1.443
  neff: 1.8
  polarization: tm
  post_process: null
  slab_offset: 2.0
  slab_xmin: -2
  spiked: true
  taper_angle: 40.0
  taper_length: 30
  wavelength: 1.554
