name: via_stack_44c03ec8
ports:
  e1:
    center:
    - -5.5
    - 0.0
    layer:
    - 49
    - 0
    name: e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  e2:
    center:
    - 0.0
    - 5.5
    layer:
    - 49
    - 0
    name: e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  e3:
    center:
    - 5.5
    - 0.0
    layer:
    - 49
    - 0
    name: e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  e4:
    center:
    - 0.0
    - -5.5
    layer:
    - 49
    - 0
    name: e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  correct_size: true
  layer_offsets: null
  layer_port: null
  layers:
  - SLAB90
  - M1
  - M2
  - MTOP
  size:
  - 11.0
  - 11.0
  slot_horizontal: false
  slot_vertical: false
  vias:
  - function: via
    settings:
      layer: VIAC
  - function: via
    settings:
      enclosure: 2
      layer: VIA1
  - function: via
    settings:
      layer: VIA2
  - null
