name: demo_cross_section_setting
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    cross_section:
      function: cross_section
      settings:
        add_pins_function_name: add_pins_inside1nm
  full:
    cross_section:
      function: cross_section
      settings:
        add_pins_function_name: add_pins_inside1nm
  function_name: demo_cross_section_setting
  info:
    cross_section:
      function: cross_section
      settings:
        add_pins_function_name: add_pins_inside1nm
    length: 10.0
    width: 0.5
  info_version: 2
  module: test_serialize
  name: demo_cross_section_setting
