function_name: dbr
info: {}
module: gdsfactory.components.dbr
name: dbr
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.476
  o2:
    center:
    - 3.18
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.524
settings:
  cross_section: xs_sc
  l1: 0.159
  l2: 0.159
  n: 10
  w1: 0.475
  w2: 0.525
