function_name: text_freetype
info: {}
module: gdsfactory.components.text_freetype
name: text_freetype
ports: {}
settings:
  font: OCR-A
  justify: left
  layer: WG
  layers: null
  size: 10
  text: abcd
