info: {}
name: edge_coupler_array_ECFt_56edc37d
settings:
  edge_coupler: Ftaper_Mgdsfactorypcomponentsptaper_SW0p2_L100_WTPTrue
  n: 5
  pitch: 127
  text: text_rectangular
  text_offset:
  - 10
  - 20
  text_rotation: 0
  x_reflection: false
