function: straight
info:
  length: 10.0
  route_info_length: 10.0
  route_info_type: xs_sc
  route_info_weight: 10.0
  route_info_xs_sc_length: 10.0
  width: 0.5
module: gdsfactory.components.straight
name: straight
settings:
  cross_section: xs_sc
  info: null
  length: 10.0
  npoints: 2
  post_process: null
