function: taper
info:
  length: 10.0
  width1: 0.5
  width2: 0.5
module: gdsfactory.components.taper
name: taper
settings:
  add_pins: true
  cross_section: xs_sc
  info: null
  length: 10.0
  port: null
  port_order_name:
  - o1
  - o2
  port_order_types:
  - optical
  - optical
  post_process: null
  width1: 0.5
  width2: null
  with_two_ports: true
