name: bend_circular_heater
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 10.0
    - 10.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  angle: 90
  cross_section: xs_sc
  heater_to_wg_distance: 1.2
  heater_width: 0.5
  layer_heater: HEATER
  npoints: null
  radius: null
  with_bbox: true
