info:
  bezier_length: 42.085
  min_bend_radius: 44.312
name: crossing45_Ccrossing_PS_3d8d9fd2
settings:
  alpha: 0.08
  cross_section: strip
  cross_section_bends: strip
  crossing: crossing
  npoints: 101
  port_spacing: 40.0
