function_name: coupler90bend
info: {}
module: gdsfactory.components.coupler90bend
name: coupler90bend
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 0.0
    - 0.7
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 10.0
    - 10.7
    layer:
    - 1
    - 0
    name: o3
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 10.7
    - 10.7
    layer:
    - 1
    - 0
    name: o4
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bend:
    function: bend_euler
  cross_section_inner: xs_sc
  cross_section_outer: xs_sc
  gap: 0.2
  radius: 10.0
