info: {}
name: loss_deembedding_ch14_2_6c0f15ec
settings:
  cross_section: strip
  grating_coupler: Fgrating_coupler_elliptical_trenches_Mgdsfactorypcomponentspgrating_coupler_elliptical_trenches_SPte_TA35
  pitch: 127
  port_name: o1
  rotation: -90
