info:
  route_info_length: 10
  route_info_strip_rib_tip_length: 10
  route_info_strip_rib_tip_taper_length: 10
  route_info_type: strip_rib_tip
  route_info_weight: 10
name: taper_cross_section_CSs_6aa7fce8
settings:
  cross_section1: strip_rib_tip
  cross_section2: rib2
  length: 10
  linear: false
  npoints: 101
  width_type: sine
