info: {}
name: pad_array_Ppad_S150_150_2dfc200f
settings:
  auto_rename_ports: false
  centered_ports: false
  columns: 1
  layer: MTOP
  pad: pad
  port_orientation: 0
  rows: 3
  size:
  - 100
  - 100
  spacing:
  - 150
  - 150
