function: extend_ports
info:
  length: 10.0
  route_info_length: 10.0
  route_info_type: xs_8bf2c479
  route_info_weight: 10.0
  route_info_xs_8bf2c479_length: 10.0
  width: 0.5
module: gdsfactory.components.extension
name: straight_extend_ports_ac2a7b25
settings:
  centered: false
  component:
    function: straight
    module: gdsfactory.components.straight
    settings:
      cross_section:
        function: cross_section
        module: gdsfactory.cross_section
        settings:
          radius: 20
          radius_min: 20
          sections:
            - hidden: false
              insets: null
              layer: SLAB90
              name: slab
              offset: 0
              offset_function: null
              port_names:
                - null
                - null
              port_types:
                - optical
                - optical
              simplify: 0.05
              width: 6.0
              width_function: null
  cross_section: null
  extension:
    function: taper_strip_to_ridge
  extension_port_names: null
  length: 5.0
  port1: o2
  port2: o1
  port_names: null
  port_type: optical
