function: resistance_sheet
info:
  resistance: 0
module: gdsfactory.components.resistance_sheet
name: resistance_sheet
settings:
  layer_offsets:
  - 0
  - 0.2
  layers:
  - SLAB90
  - NPP
  ohms_per_square: null
  pad:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
      - SLAB90
      - NPP
      - M1
      size:
      - 80
      - 80
      vias:
      - null
      - null
      - function: via
        module: gdsfactory.components.via
        settings:
          layer: VIAC
  pad_pitch: 100.0
  port_orientation1: 180
  port_orientation2: 0
  post_process: null
  width: 10
