name: coupler_gap0p2_length5p0_add_fiber_array_39152c1b
ports:
  opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-loopback0:
    center:
    - -315.0
    - -55.4
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-loopback0
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-loopback1:
    center:
    - 320.0
    - -55.4
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-loopback1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-o1:
    center:
    - -188.0
    - -55.4
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-o1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-o2:
    center:
    - -61.0
    - -55.4
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-o3:
    center:
    - 66.0
    - -55.4
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-o3
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-o4:
    center:
    - 193.0
    - -55.4
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-coupler_gap0p2_length5p0-o4
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    component:
      component: coupler
      settings:
        gap: 0.2
        length: 5.0
    optical_routing_type: 1
  child:
    changed:
      gap: 0.2
      length: 5.0
    child: null
    default:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section: strip
      dx: 10.0
      dy: 4.0
      gap: 0.236
      length: 20.0
    full:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section: strip
      dx: 10.0
      dy: 4.0
      gap: 0.2
      length: 5.0
    function_name: coupler
    info:
      length: 10.19
      min_bend_radius: 11.744
    info_version: 2
    module: gdsfactory.components.coupler
    name: coupler_gap0p2_length5p0
  default:
    component:
      function: straight
    component_name: null
    cross_section: strip
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
      settings:
        get_input_label_text_function:
          function: get_input_label_text_dash
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label: LABEL
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  full:
    component:
      component: coupler
      settings:
        gap: 0.2
        length: 5.0
    component_name: null
    cross_section: strip
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
      settings:
        get_input_label_text_function:
          function: get_input_label_text_dash
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label: LABEL
    optical_routing_type: 1
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  function_name: add_fiber_array
  info:
    grating_coupler:
      period: 0.676
      polarization: te
      wavelength: 1.53
    length: 10.19
    min_bend_radius: 11.744
  info_version: 2
  module: gdsfactory.routing.add_fiber_array
  name: coupler_gap0p2_length5p0_add_fiber_array_39152c1b
