function_name: mzi_pads_center
info: {}
module: gdsfactory.components.mzi_pads_center
name: mzi_pads_center
ports:
  bot_l_e1:
    center:
    - 19.6
    - -80.625
    layer:
    - 49
    - 0
    name: bot_l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  bot_l_e2:
    center:
    - 25.1
    - -75.125
    layer:
    - 49
    - 0
    name: bot_l_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  bot_l_e3:
    center:
    - 30.6
    - -80.625
    layer:
    - 49
    - 0
    name: bot_l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  bot_l_e4:
    center:
    - 25.1
    - -86.125
    layer:
    - 49
    - 0
    name: bot_l_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  bot_r_e1:
    center:
    - 540.4
    - -80.625
    layer:
    - 49
    - 0
    name: bot_r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  bot_r_e2:
    center:
    - 545.9
    - -75.125
    layer:
    - 49
    - 0
    name: bot_r_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  bot_r_e3:
    center:
    - 551.4
    - -80.625
    layer:
    - 49
    - 0
    name: bot_r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  bot_r_e4:
    center:
    - 545.9
    - -86.125
    layer:
    - 49
    - 0
    name: bot_r_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 581.02
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  top_l_e1:
    center:
    - 19.6
    - 60.625
    layer:
    - 49
    - 0
    name: top_l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e2:
    center:
    - 25.1
    - 66.125
    layer:
    - 49
    - 0
    name: top_l_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e3:
    center:
    - 30.6
    - 60.625
    layer:
    - 49
    - 0
    name: top_l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e4:
    center:
    - 25.1
    - 55.125
    layer:
    - 49
    - 0
    name: top_l_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e1:
    center:
    - 540.4
    - 60.625
    layer:
    - 49
    - 0
    name: top_r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e2:
    center:
    - 545.9
    - 66.125
    layer:
    - 49
    - 0
    name: top_r_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e3:
    center:
    - 551.4
    - 60.625
    layer:
    - 49
    - 0
    name: top_r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e4:
    center:
    - 545.9
    - 55.125
    layer:
    - 49
    - 0
    name: top_r_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  cross_section: xs_sc
  cross_section_metal: xs_metal_routing
  delta_length: 40.0
  length_x: 500
  length_y: 40
  mzi:
    function: mzi
  mzi_gnd_bot: bot_r_e2
  mzi_gnd_top: top_l_e2
  mzi_sig_bot: bot_l_e2
  mzi_sig_top: top_r_e2
  pad:
    function: pad
    module: gdsfactory.components.pad
    settings:
      size:
      - 80
      - 80
  pad_gnd_bot: e4_1_2
  pad_gnd_top: e2_1_2
  pad_sig_bot: e1_1_1
  pad_sig_top: e3_1_3
  pad_spacing: pad_spacing
  ps_bot:
    function: straight_heater_metal_undercut
    module: gdsfactory.components.straight_heater_metal
    settings:
      with_undercut: false
  ps_top:
    function: straight_heater_metal_undercut
    module: gdsfactory.components.straight_heater_metal
    settings:
      with_undercut: false
