function: taper_strip_to_ridge
info:
  length: 20.0
module: gdsfactory.components.taper
name: taper_strip_to_ridge_daef8427
settings:
  cross_section: xs_sc
  layer_slab: WGN
  layer_wg: WG
  length: 20.0
  post_process: null
  w_slab1: 0.15
  w_slab2: 1.0
  width1: 0.5
  width2: 0.15
