info:
  dx: 10
  dy: 10
  length: 15.708
name: bend_circular_heater_RN_4b4fbbb3
settings:
  allow_min_radius_violation: false
  angle: 90
  cross_section: strip
  heater_to_wg_distance: 1.2
  heater_width: 0.5
  layer_heater: HEATER
