info:
  length: 999.999
  straight_length: 48.892
name: spiral_racetrack_fixed__0024322a
settings:
  bend: bend_circular
  bend_s: bend_s
  cross_section: strip
  in_out_port_spacing: 150
  length: 1000
  min_spacing: 5
  n_straight_sections: 8
  straight: straight
