info:
  resistance: 0
name: resistance_sheet_W10_LH_1b3e3b4b
settings:
  layer_offsets:
  - 0
  - 0.2
  layers:
  - HEATER
  pad: via_stack_heater_mtop
  pad_pitch: 100
  pad_port_name: e4
  pad_size:
  - 50.0
  - 50.0
  width: 10
