info: {}
name: cdsem_straight_density__211dadfd
settings:
  cross_section: strip
  gaps:
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  label: ''
  length: 420
  text: Ftext_rectangular_Mgdsfactorypcomponentsptext_rectangular_SS1
  widths:
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
