function_name: cdsem_bend180
info: {}
module: gdsfactory.components.cdsem_bend180
name: cdsem_bend180
ports: {}
settings:
  bend90: bend_circular
  cross_section: xs_sc
  radius: 10.0
  straight: straight
  text:
    function: text_rectangular
    module: gdsfactory.components.text_rectangular
    settings:
      size: 1
  wg_length: 420.0
  width: 0.5
