info:
  bend180_radius: 5.0
  min_bend_radius: 364.774
name: delay_snake_sbend_L100__aa6d2bff
settings:
  bend: bend_euler
  cross_section: strip
  length: 100
  length1: 0
  length4: 0
  radius: 5
  sbend: bend_s
  sbend_xsize: 100
  waveguide_spacing: 5
