function: resistance_meander
info: {}
module: gdsfactory.components.resistance_meander
name: resistance_meander
settings:
  gnd_layer: MTOP
  num_squares: 1000
  pad_layer: MTOP
  pad_size:
  - 50.0
  - 50.0
  res_layer: MTOP
  width: 1.0
