info:
  length: 20
name: taper_strip_to_ridge_L2_5eb7f501
settings:
  cross_section: strip
  layer_slab: WGN
  layer_wg: WG
  length: 20
  use_slab_port: true
  w_slab1: 0.15
  w_slab2: 1
  width1: 0.5
  width2: 0.15
