name: taper_cross_section_4a5f6ea9
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  cross_section1:
    function: cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
      sections:
      - hidden: false
        insets: null
        layer: SLAB90
        name: slab
        offset: 0
        offset_function: null
        port_names:
        - null
        - null
        port_types:
        - optical
        - optical
        simplify: null
        width: 0.2
        width_function: null
  cross_section2: xs_rc
  length: 10
  linear: false
  npoints: 101
  width_type: parabolic
