info:
  xsize: 11.0
  ysize: 11.0
name: via_stack_S11_11_LM1_M2_e0ab0502
settings:
  correct_size: true
  layers:
  - M1
  - M2
  - MTOP
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  size:
  - 11.0
  - 11.0
  slot_horizontal: false
  slot_vertical: false
  vias:
  - via1
  - via2
  - null
