info:
  polarization: te
  wavelength: 1.554
name: grating_coupler_ellipti_30151d1e
settings:
  bias_gap: 0
  cross_section: strip
  fiber_angle: 15.0
  gaps:
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  layer_slab: SLAB150
  nclad: 1.443
  polarization: te
  spiked: 1
  taper_angle: 60.0
  taper_length: 16.6
  taper_to_slab_offset: -3.0
  wavelength: 1.554
  widths:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
