name: rectangle_size1300__2600_die_bbox
ports: {}
settings:
  changed: {}
  child:
    changed:
      size:
      - 1300
      - 2600
    child: null
    default:
      centered: false
      layer: WG
      port_orientations:
      - 180
      - 90
      - 0
      - -90
      port_type: electrical
      size:
      - 4.0
      - 2.0
    full:
      centered: false
      layer: WG
      port_orientations:
      - 180
      - 90
      - 0
      - -90
      port_type: electrical
      size:
      - 1300
      - 2600
    function_name: rectangle
    info: {}
    info_version: 2
    module: gdsfactory.components.rectangle
    name: rectangle_size1300__2600
  default:
    component:
      function: rectangle
      settings:
        size:
        - 1300
        - 2600
    die_name: null
    layer: M3
    padding: 10.0
    street_length: null
    street_width: 100.0
    text_anchor: sw
    text_size: 100.0
  full:
    component:
      function: rectangle
      settings:
        size:
        - 1300
        - 2600
    die_name: null
    layer: M3
    padding: 10.0
    street_length: null
    street_width: 100.0
    text_anchor: sw
    text_size: 100.0
  function_name: die_bbox
  info: {}
  info_version: 2
  module: gdsfactory.components.die_bbox
  name: rectangle_size1300__2600_die_bbox
