info: {}
name: mzi_gdsfactorypcomponen_f7d7b0f0
settings:
  add_optical_ports_arms: false
  auto_rename_ports: true
  bend: bend_euler
  combiner: mmi1x2
  cross_section: strip
  delta_length: 10
  length_x: 0.1
  length_y: 2
  min_length: 0.01
  mirror_bot: false
  nbends: 2
  port1: o1
  port2: o2
  port_e0_combiner: o3
  port_e0_splitter: o3
  port_e1_combiner: o2
  port_e1_splitter: o2
  splitter: mmi1x2
  straight: straight
  with_splitter: true
