function: mimcap
info: {}
module: gdsfactory.components.mimcap
name: mimcap
settings:
  gap_top_metal: 2
  layers_bot:
    - M2
  offsets_bot:
    - 0.5
  size:
    - 64
    - 64
  via_stack:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
        - M2
        - MTOP
      vias:
        - function: via
          module: gdsfactory.components.via
          settings:
            layer: VIA2
        - null
  width_contact: 2.5
