name: die_bbox_frame
ports: {}
settings:
  bbox:
  - - -1.0
    - -1.0
  - - 3.0
    - 4.0
  die_name: null
  layer: MTOP
  padding: 10.0
  street_length: 1000.0
  street_width: 100.0
  text_anchor: sw
  text_size: 100.0
