function: ring_crow
info: {}
module: gdsfactory.components.ring_crow
name: ring_crow
settings:
  bends:
  - function: bend_circular
  - function: bend_circular
  - function: bend_circular
  gaps:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  input_straight_cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
  output_straight_cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
  radius:
  - 10.0
  - 10.0
  - 10.0
  ring_cross_sections:
  - function: cross_section
    module: gdsfactory.cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
  - function: cross_section
    module: gdsfactory.cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
  - function: cross_section
    module: gdsfactory.cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
