function_name: die
info: {}
module: gdsfactory.components.die
name: die
ports: {}
settings:
  bbox_layer: FLOORPLAN
  bbox_layers: null
  die_name: chip99
  draw_corners: false
  layer: FLOORPLAN
  layers: null
  size:
  - 10000.0
  - 10000.0
  street_length: 1000.0
  street_width: 100.0
  text:
    function: text
  text_location: SW
  text_size: 100.0
