function: bbox
info: {}
module: gdsfactory.components.bbox
name: bbox
settings:
  bbox:
    - - -1.0
      - -1.0
    - - 3.0
      - 4.0
  bottom: 0
  layer:
    - 1
    - 0
  left: 0
  right: 0
  top: 0
