function: add_trenches
info: {}
module: gdsfactory.components.add_trenches
name: ring_single_add_trenches_06939900
settings:
  bot: true
  component:
    function: ring_single
  cross_section: xs_rc_with_trenches
  layer_trench:
  - 1
  - 7
  left: false
  right: false
  top: true
  width_trench: 3
