info:
  dy: 10.0
  length: 16.637
  min_bend_radius: 7.061
  radius: 10.0
  route_info_length: 16.637
  route_info_min_bend_radius: 7.061
  route_info_n_bend_90: 1.0
  route_info_type: xs_34e31a19
  route_info_weight: 16.637
  route_info_xs_34e31a19_length: 16.637
name: bend_euler_RNone_A90_P0_d7c3a5a9
settings:
  allow_min_radius_violation: false
  angle: 90.0
  cross_section: strip
  p: 0.5
  with_arc_floorplan: true
