info: {}
name: via_chain_NV100_C10_Vvi_a44e7637
settings:
  cols: 10
  contact: via_stack_m2_m3
  layers_bot:
  - M1
  layers_top:
  - M2
  min_metal_spacing: 1.0
  num_vias: 100
  offsets_bot:
  - 0
  offsets_top:
  - 0
  via: via1
  via_min_enclosure: 1.0
