name: None_add_trenches_06939900
ports:
  o1:
    center:
    - -17.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 13.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bot: true
  component:
    function: ring_single
  cross_section: xs_rc_with_trenches
  left: false
  right: false
  top: true
