name: straight
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    add_bbox: null
    add_pins: true
    cross_section: xs_sc
    layer: null
    length: 10.0
    npoints: 2
    width: null
  full:
    add_bbox: null
    add_pins: true
    cross_section: xs_sc
    layer: null
    length: 10.0
    npoints: 2
    width: null
  function_name: straight
  info:
    cross_section: xs_sc
    length: 10.0
    route_info:
      length: 10.0
      type: xs_sc
      weight: 10.0
      xs_sc_length: 10.0
    width: 0.5
  info_version: 2
  module: gdsfactory.components.straight
  name: straight
