function: coupler_asymmetric
info: {}
module: gdsfactory.components.coupler_asymmetric
name: coupler_asymmetric
settings:
  bend:
    function: bend_s
  cross_section: xs_sc_no_pins
  dx: 10.0
  dy: 2.5
  gap: 0.234
