name: straight_0dd74e54_extend_ports_90a9fa88
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 20.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    component:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            add_pins_function_name: add_pins_inside1nm
            sections:
            - hidden: false
              insets: null
              layer: SLAB90
              name: slab
              offset: 0
              offset_function: null
              port_names:
              - null
              - null
              port_types:
              - optical
              - optical
              simplify: 0.05
              width: 6.0
              width_function: null
    extension:
      function: taper_strip_to_ridge
    port1: o2
    port2: o1
  child: null
  default:
    centered: false
    component:
      function: mmi1x2
    cross_section: null
    extension: null
    extension_port_names: null
    length: 5.0
    port1: null
    port2: null
    port_names: null
    port_type: optical
  full:
    centered: false
    component:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            add_pins_function_name: add_pins_inside1nm
            sections:
            - hidden: false
              insets: null
              layer: SLAB90
              name: slab
              offset: 0
              offset_function: null
              port_names:
              - null
              - null
              port_types:
              - optical
              - optical
              simplify: 0.05
              width: 6.0
              width_function: null
    cross_section: null
    extension:
      function: taper_strip_to_ridge
    extension_port_names: null
    length: 5.0
    port1: o2
    port2: o1
    port_names: null
    port_type: optical
  function_name: extend_ports
  info:
    cross_section:
      function: cross_section
      settings:
        add_pins_function_name: add_pins_inside1nm
        sections:
        - hidden: false
          insets: null
          layer: SLAB90
          name: slab
          offset: 0
          offset_function: null
          port_names:
          - null
          - null
          port_types:
          - optical
          - optical
          simplify: 0.05
          width: 6.0
          width_function: null
    length: 10.0
    route_info:
      length: 10.0
      type: xs_f0722844
      weight: 10.0
      xs_f0722844_length: 10.0
    width: 0.5
  info_version: 2
  module: gdsfactory.components.extension
  name: straight_0dd74e54_extend_ports_90a9fa88
