info: {}
name: add_fiber_array_optical_e4327793
settings:
  component: Fstraight_heater_metal_undercut_Mgdsfactorypcomponentspwaveguidespstraight_heater_metal_SWUFalse_LSI0p1_LU5_LUS0
  cross_section_metal: metal_routing
  electrical_port_orientation: 90
  grating_coupler: Fgrating_coupler_elliptical_trenches_Mgdsfactorypcomponentspgrating_couplerspgrating_coupler_elliptical_trenches_SPte_TA35
  pad: pad
  pad_gc_spacing: 250
  pad_pitch: 100
  pitch: 127
  with_loopback: true
