name: straight_length20_width2_add_tapers_b2a8d58e_add_fiber_array_09a0105a
ports:
  opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2-loopback0:
    center:
    - -180.5
    - -28.5
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2-loopback0
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2-loopback1:
    center:
    - 200.5
    - -28.5
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2-loopback1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2-o1:
    center:
    - -53.5
    - -28.5
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2-o1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2-o2:
    center:
    - 73.5
    - -28.5
    layer:
    - 1
    - 0
    name: opt-grating_coupler_elliptical_trenches_taper_angle35-straight_length20_width2-o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    component:
      component: add_tapers
      settings:
        component:
          component: straight
          settings:
            length: 20
            width: 2
    optical_routing_type: 0
  child:
    changed:
      component:
        component: straight
        settings:
          length: 20
          width: 2
    child:
      changed:
        length: 20
        width: 2
      child: null
      default:
        cross_section: strip
        length: 10.0
        npoints: 2
        with_bbox: true
      full:
        cross_section: strip
        length: 20
        npoints: 2
        width: 2
        with_bbox: true
      function_name: straight
      info:
        cross_section: strip
        function_name: cross_section
        length: 20
        route_info:
          length: 20
          strip_length: 20
          type: strip
          weight: 20
        settings:
          add_bbox: null
          add_pins:
            function: add_pins
            settings:
              function:
                function: add_pin_rectangle_inside
                settings:
                  layer_label: null
                  pin_length: 0.001
          auto_widen: false
          auto_widen_minimum_length: 200.0
          bbox_layers: null
          bbox_offsets: null
          cladding_layers: null
          cladding_offsets: null
          cladding_simplify: null
          decorator: null
          end_straight_length: 0.01
          gap: 3.0
          info:
            type: strip
          layer: WG
          min_length: 0.01
          mirror: false
          name: strip
          offset: 0
          port_names:
          - o1
          - o2
          port_types:
          - optical
          - optical
          radius: 10.0
          sections: null
          snap_to_grid: null
          start_straight_length: 0.01
          taper_length: 10.0
          width: 2
          width_wide: null
        type: strip
        width: 2.0
      info_version: 2
      module: gdsfactory.components.straight
      name: straight_length20_width2
    default:
      ports: null
      select_ports:
        function: select_ports
        settings:
          port_type: optical
      taper:
        function: taper
      taper_port_name1: o1
      taper_port_name2: o2
    full:
      component:
        component: straight
        settings:
          length: 20
          width: 2
      ports: null
      select_ports:
        function: select_ports
        settings:
          port_type: optical
      taper:
        function: taper
      taper_port_name1: o1
      taper_port_name2: o2
    function_name: add_tapers
    info:
      cross_section: strip
      function_name: cross_section
      length: 20
      route_info:
        length: 20
        strip_length: 20
        type: strip
        weight: 20
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
          settings:
            function:
              function: add_pin_rectangle_inside
              settings:
                layer_label: null
                pin_length: 0.001
        auto_widen: false
        auto_widen_minimum_length: 200.0
        bbox_layers: null
        bbox_offsets: null
        cladding_layers: null
        cladding_offsets: null
        cladding_simplify: null
        decorator: null
        end_straight_length: 0.01
        gap: 3.0
        info:
          type: strip
        layer: WG
        min_length: 0.01
        mirror: false
        name: strip
        offset: 0
        port_names:
        - o1
        - o2
        port_types:
        - optical
        - optical
        radius: 10.0
        sections: null
        snap_to_grid: null
        start_straight_length: 0.01
        taper_length: 10.0
        width: 2
        width_wide: null
      type: strip
      width: 2.0
    info_version: 2
    module: gdsfactory.add_tapers
    name: straight_length20_width2_add_tapers_b2a8d58e
  default:
    component:
      function: straight
    component_name: null
    cross_section: strip
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
      settings:
        get_input_label_text_function:
          function: get_input_label_text_dash
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label: LABEL
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  full:
    component:
      component: add_tapers
      settings:
        component:
          component: straight
          settings:
            length: 20
            width: 2
    component_name: null
    cross_section: strip
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
      settings:
        get_input_label_text_function:
          function: get_input_label_text_dash
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label: LABEL
    optical_routing_type: 0
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  function_name: add_fiber_array
  info:
    cross_section: strip
    function_name: cross_section
    grating_coupler:
      period: 0.676
      polarization: te
      wavelength: 1.53
    length: 20
    route_info:
      length: 20
      strip_length: 20
      type: strip
      weight: 20
    settings:
      add_bbox: null
      add_pins:
        function: add_pins
        settings:
          function:
            function: add_pin_rectangle_inside
            settings:
              layer_label: null
              pin_length: 0.001
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers: null
      bbox_offsets: null
      cladding_layers: null
      cladding_offsets: null
      cladding_simplify: null
      decorator: null
      end_straight_length: 0.01
      gap: 3.0
      info:
        type: strip
      layer: WG
      min_length: 0.01
      mirror: false
      name: strip
      offset: 0
      port_names:
      - o1
      - o2
      port_types:
      - optical
      - optical
      radius: 10.0
      sections: null
      snap_to_grid: null
      start_straight_length: 0.01
      taper_length: 10.0
      width: 2
      width_wide: null
    type: strip
    width: 2.0
  info_version: 2
  module: gdsfactory.routing.add_fiber_array
  name: straight_length20_width2_add_tapers_b2a8d58e_add_fiber_array_09a0105a
