function_name: taper
info:
  length: 100.0
  width1: 0.5
  width2: 0.2
module: gdsfactory.components.taper
name: taper_abf5825d
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  add_pins: true
  cross_section: xs_sc
  length: 100
  port: null
  port_order_name:
  - o1
  - o2
  port_order_types:
  - optical
  - optical
  width1: 0.5
  width2: 0.2
  with_bbox: true
  with_two_ports: false
