name: cross
ports: {}
settings:
  changed: {}
  child: null
  default:
    layer: WG
    length: 10.0
    port_type: null
    width: 3.0
  full:
    layer: WG
    length: 10.0
    port_type: null
    width: 3.0
  function_name: cross
  info: {}
  info_version: 2
  module: gdsfactory.components.cross
  name: cross
