name: cdsem_straight_density
ports: {}
settings:
  cross_section: xs_sc
  gaps:
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  label: ''
  length: 420.0
  text:
    function: text_rectangular
    settings:
      size: 1
  widths:
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
