function_name: greek_cross_offset_pads
info: {}
module: gdsfactory.components.greek_cross
name: greek_cross_offset_pads
ports: {}
settings:
  contact_buffer: 10
  contact_layers:
  - WG
  - NPP
  contact_offset: 10
  cross_implant_layers:
  - N
  cross_implant_length: 30.0
  cross_implant_width: 2.0
  cross_struct_layers:
  - WG
  cross_struct_length: 30.0
  cross_struct_width: 1.0
  pad_width: 50
