function: cdc
info: {}
module: gdsfactory.components.cdc
name: cdc
settings:
  cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      radius: 10
      radius_min: 5
  dc: 0.5
  dx: 10.0
  dy: 1.8
  fin_size:
    - 0.2
    - 0.05
  fins: false
  gap: 0.5
  length: 30.0
  period: 0.22
  width_bot: 0.75
  width_top: 2.0
