info: {}
name: delay_snake_L1600_L0_L0_4d5eb36d
settings:
  bend180: Fbend_euler_Mgdsfactorypcomponentspbendspbend_euler_SA180
  cross_section: strip
  length: 1600.0
  length0: 0.0
  length2: 0.0
  n: 2
