function: grating_coupler_rectangular_arbitrary
info:
  polarization: te
  wavelength: 1.55
module: gdsfactory.components.grating_coupler_rectangular_arbitrary
name: grating_coupler_rectangular_arbitrary
settings:
  cross_section: xs_sc
  fiber_angle: null
  gaps:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  info: null
  layer_grating: null
  layer_slab: null
  length_taper: 150.0
  polarization: te
  post_process: null
  slab_offset: 1.0
  slab_xmin: -1.0
  taper:
    function: taper
  wavelength: 1.55
  width_grating: 11.0
  widths:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
