function_name: cutback_bend180
info:
  n_bends: 82
module: gdsfactory.components.cutback_bend
name: cutback_bend180
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 203.28
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  cols: 6
  component:
    function: bend_euler
    settings:
      angle: 180
  rows: 6
  spacing: 3
  straight:
    function: straight
  straight_length: 5.0
