name: None_add_electrical_pads_top_67ba37bb
ports:
  elec-mzi_2e88f57c-1:
    center:
    - 578.56
    - 178.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-1
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-2:
    center:
    - 428.56
    - 178.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-2
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-3:
    center:
    - 278.56
    - 178.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-3
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-4:
    center:
    - 128.56
    - 178.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-5:
    center:
    - -21.44
    - 178.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-5
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-6:
    center:
    - -171.44
    - 178.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-6
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-7:
    center:
    - -321.44
    - 178.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-7
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 100.0
  elec-mzi_2e88f57c-8:
    center:
    - -471.44
    - 178.125
    layer:
    - 49
    - 0
    name: elec-mzi_2e88f57c-8
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 100.0
  o1:
    center:
    - -10.0
    - -0.625
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - -10.0
    - 0.625
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 117.12
    - 0.625
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 117.12
    - -0.625
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  component:
    function: mzi
    module: gdsfactory.components.mzi
    settings:
      add_electrical_ports_bot: true
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: xs_sc
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      extend_ports_straight_x: null
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
  direction: top
  layer: MTOP
  pad_array:
    function: pad_array
  port_names: null
  select_ports:
    function: select_ports
    settings:
      port_type: electrical
  spacing:
  - 0.0
  - 100.0
