name: mzi_2e88f57c_add_fiber__8b3364c2
ports:
  opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-loopback0:
    center:
    - -263.9
    - -81.3
    layer:
    - 1
    - 0
    name: opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-loopback0
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-loopback1:
    center:
    - 371.1
    - -81.3
    layer:
    - 1
    - 0
    name: opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-loopback1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-o1:
    center:
    - -136.9
    - -81.3
    layer:
    - 1
    - 0
    name: opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-o1
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-o2:
    center:
    - -9.9
    - -81.3
    layer:
    - 1
    - 0
    name: opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-o3:
    center:
    - 117.1
    - -81.3
    layer:
    - 1
    - 0
    name: opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-o3
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-o4:
    center:
    - 244.1
    - -81.3
    layer:
    - 1
    - 0
    name: opt-grating_coupler_ellipti_dd7f7af4-mzi_2e88f57c-o4
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  top_l_e1:
    center:
    - 19.5
    - 22.625
    layer:
    - 49
    - 0
    name: top_l_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e2:
    center:
    - 25.0
    - 28.125
    layer:
    - 49
    - 0
    name: top_l_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e3:
    center:
    - 30.5
    - 22.625
    layer:
    - 49
    - 0
    name: top_l_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e4:
    center:
    - 25.0
    - 17.125
    layer:
    - 49
    - 0
    name: top_l_e4
    orientation: 270
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e1:
    center:
    - 76.6
    - 22.625
    layer:
    - 49
    - 0
    name: top_r_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e2:
    center:
    - 82.1
    - 28.125
    layer:
    - 49
    - 0
    name: top_r_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e3:
    center:
    - 87.6
    - 22.625
    layer:
    - 49
    - 0
    name: top_r_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e4:
    center:
    - 82.1
    - 17.125
    layer:
    - 49
    - 0
    name: top_r_e4
    orientation: 270
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  changed:
    component:
      component: mzi
      settings:
        combiner:
          function: mmi2x2
        port_e0_combiner: o4
        port_e0_splitter: o4
        port_e1_combiner: o3
        port_e1_splitter: o3
        splitter:
          function: mmi2x2
        straight_x_top: straight_heater_metal
  child:
    changed:
      combiner:
        function: mmi2x2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight_x_top: straight_heater_metal
    child: null
    default:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner: null
      cross_section: strip
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o3
      port_e0_splitter: o3
      port_e1_combiner: o2
      port_e1_splitter: o2
      splitter: mmi1x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: null
      straight_y: null
      with_splitter: true
    full:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: strip
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
    function_name: mzi
    info: {}
    info_version: 2
    module: gdsfactory.components.mzi
    name: mzi_2e88f57c
  default:
    component:
      function: straight
    component_name: null
    cross_section: strip
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
      settings:
        get_input_label_text_function:
          function: get_input_label_text_dash
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label: LABEL
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  full:
    component:
      component: mzi
      settings:
        combiner:
          function: mmi2x2
        port_e0_combiner: o4
        port_e0_splitter: o4
        port_e1_combiner: o3
        port_e1_splitter: o3
        splitter:
          function: mmi2x2
        straight_x_top: straight_heater_metal
    component_name: null
    cross_section: strip
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
      settings:
        get_input_label_text_function:
          function: get_input_label_text_dash
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label: LABEL
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  function_name: add_fiber_array
  info:
    grating_coupler:
      period: 0.676
      polarization: te
      wavelength: 1.53
  info_version: 2
  module: gdsfactory.routing.add_fiber_array
  name: mzi_2e88f57c_add_fiber__8b3364c2
