function: add_pads_bot
info: {}
module: gdsfactory.routing.add_pads
name: mzi_add_pads_bot_componentmzi_669c248e
settings:
  bend: wire_corner
  component:
    function: mzi
    module: gdsfactory.components.mzi
    settings:
      add_electrical_ports_bot: true
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: strip
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      extend_ports_straight_x: null
      length_x: 100
      length_y: 2.0
      min_length: 0.01
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
  component_name: null
  cross_section: metal_routing
  get_input_labels_function: null
  layer_label: TEXT
  min_length: null
  optical_routing_type: 1
  pad:
    function: pad
    module: gdsfactory.components.pad
    settings:
      size: pad_size
  pad_port_labels: null
  pad_port_name: e1
  pad_pitch: pad_pitch
  port_names: null
  select_ports:
    function: select_ports
    module: gdsfactory.port
    settings:
      port_type: electrical
  straight_separation: 20.0
  with_loopback: false
