name: rectangle_with_slits
ports: {}
settings:
  centered: false
  layer: WG
  layer_slit: SLAB150
  port_type: null
  size:
  - 100.0
  - 200.0
  slit_enclosure: 10
  slit_size:
  - 1.0
  - 1.0
  slit_spacing:
  - 20
  - 20
