name: taper_strip_to_ridge
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 10.0
    - 0.0
    layer:
    - 3
    - 0
    name: o2
    orientation: 0
    port_type: optical
    shear_angle: null
    width: 6.0
settings:
  cross_section: xs_sc
  layer_slab: SLAB90
  layer_wg: WG
  length: 10.0
  w_slab1: 0.15
  w_slab2: 6.0
  width1: 0.5
  width2: 0.5
