info: {}
name: mzi_DL10_LY2_LX200_Bben_ebed402c
settings:
  add_optical_ports_arms: false
  auto_rename_ports: true
  bend: bend_euler
  cross_section: strip
  delta_length: 10
  length_x: 200
  length_y: 2
  min_length: 0.01
  mirror_bot: false
  nbends: 2
  port_e0_combiner: o3
  port_e0_splitter: o3
  port_e1_combiner: o2
  port_e1_splitter: o2
  splitter: mmi1x2
  straight: straight
  straight_x_bot: straight_pin
  straight_x_top: straight_pin
  with_splitter: true
