function: add_fiber_single
info: {}
module: gdsfactory.routing.add_fiber_single
name: mzi_add_fiber_single_componentmzi_669c248e
settings:
  bend:
    function: bend_euler
  component:
    function: mzi
    module: gdsfactory.components.mzi
    settings:
      add_electrical_ports_bot: true
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: strip
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      extend_ports_straight_x: null
      length_x: 100
      length_y: 2.0
      min_length: 0.01
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
  component_name: null
  cross_section: strip
  fiber_spacing: 50
  gc_port_name: o1
  gc_port_name_fiber: o2
  get_input_label_text_function:
    function: get_input_label_text_dash
  get_input_label_text_loopback_function:
    function: get_input_label_text_dash_loopback
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    module: gdsfactory.components.grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  io_rotation: null
  layer_label: null
  loopback_xspacing: 50.0
  min_input_to_output_spacing: 200.0
  optical_routing_type: 2
  route_filter:
    function: route_single_from_waypoints
  select_ports:
    function: select_ports
    module: gdsfactory.port
    settings:
      port_type: optical
  straight:
    function: straight
  with_loopback: true
  zero_port: null
