info:
  components: 88
name: cutback_splitter_Cmmi1x_7c0cdfa9
settings:
  bend180: bend_euler180
  cols: 4
  component: mmi1x2
  cross_section: strip
  mirror: 0
  port1: o1
  port2: o2
  port3: o3
  rows: 5
  straight: straight
