name: straight_heater_doped_rib
ports:
  bot_e1:
    center:
    - -0.2
    - -20.0
    layer:
    - 49
    - 0
    name: bot_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  bot_e2:
    center:
    - 154.8
    - -15.0
    layer:
    - 49
    - 0
    name: bot_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 310.0
  bot_e3:
    center:
    - 309.8
    - -20.0
    layer:
    - 49
    - 0
    name: bot_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  bot_e4:
    center:
    - 154.8
    - -25.0
    layer:
    - 49
    - 0
    name: bot_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 310.0
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 310.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  top_e1:
    center:
    - -0.2
    - 20.0
    layer:
    - 49
    - 0
    name: top_e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  top_e2:
    center:
    - 154.8
    - 25.0
    layer:
    - 49
    - 0
    name: top_e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 310.0
  top_e3:
    center:
    - 309.8
    - 20.0
    layer:
    - 49
    - 0
    name: top_e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  top_e4:
    center:
    - 154.8
    - 15.0
    layer:
    - 49
    - 0
    name: top_e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 310.0
settings:
  changed: {}
  child: null
  default:
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
          settings:
            function:
              function: add_pin_rectangle_inside
              settings:
                layer_label: null
                pin_length: 0.001
        info:
          type: strip
        name: strip
        radius: 20
        sections:
        - hidden: false
          insets: null
          layer: SLAB90
          name: slab
          offset: 0
          port_names:
          - null
          - null
          port_types:
          - optical
          - optical
          simplify: null
          width: 0.2
    cross_section_heater:
      function: rib_heater_doped
    heater_gap: 0.8
    heater_width: 2.0
    length: 320.0
    nsections: 3
    taper:
      function: taper_cross_section
    via_stack:
      function: via_stack
      settings:
        layers:
        - SLAB90
        - NPP
        - M1
        vias:
        - null
        - null
        - function: via
          settings:
            layer: VIAC
    via_stack_gap: 0.0
    via_stack_metal:
      function: via_stack
      settings:
        layers:
        - M1
        - M2
        - M3
        vias:
        - function: via
          settings:
            enclosure: 2
            layer: VIA1
        - function: via
          settings:
            layer: VIA2
        - null
    via_stack_metal_size:
    - 10.0
    - 10.0
    via_stack_size:
    - 10.0
    - 10.0
    width: 0.5
    with_taper1: true
    with_taper2: true
    xoffset_tip1: 0.2
    xoffset_tip2: 0.4
  full:
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
          settings:
            function:
              function: add_pin_rectangle_inside
              settings:
                layer_label: null
                pin_length: 0.001
        info:
          type: strip
        name: strip
        radius: 20
        sections:
        - hidden: false
          insets: null
          layer: SLAB90
          name: slab
          offset: 0
          port_names:
          - null
          - null
          port_types:
          - optical
          - optical
          simplify: null
          width: 0.2
    cross_section_heater:
      function: rib_heater_doped
    heater_gap: 0.8
    heater_width: 2.0
    length: 320.0
    nsections: 3
    taper:
      function: taper_cross_section
    via_stack:
      function: via_stack
      settings:
        layers:
        - SLAB90
        - NPP
        - M1
        vias:
        - null
        - null
        - function: via
          settings:
            layer: VIAC
    via_stack_gap: 0.0
    via_stack_metal:
      function: via_stack
      settings:
        layers:
        - M1
        - M2
        - M3
        vias:
        - function: via
          settings:
            enclosure: 2
            layer: VIA1
        - function: via
          settings:
            layer: VIA2
        - null
    via_stack_metal_size:
    - 10.0
    - 10.0
    via_stack_size:
    - 10.0
    - 10.0
    width: 0.5
    with_taper1: true
    with_taper2: true
    xoffset_tip1: 0.2
    xoffset_tip2: 0.4
  function_name: straight_heater_doped_rib
  info: {}
  info_version: 2
  module: gdsfactory.components.straight_heater_doped_rib
  name: straight_heater_doped_rib
