info:
  resistance: 0
name: resistance_sheet_W10_LS_84c30ba4
settings:
  layer_offsets:
  - 0
  - 0.2
  layers:
  - SLAB90
  - NPP
  pad: Fvia_stack_Mgdsfactorypcomponentspvia_stack_SLSLAB90_NPP_M1_VNone_None_Fvia_Mgdsfactorypcomponentspvia_SLVIAC_S80_80
  pad_pitch: 100
  pad_port_name: e4
  pad_size:
  - 50
  - 50
  width: 10
