name: mzi_a62d3423
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 81.12
    - 0.625
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 81.12
    - -0.625
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  add_electrical_ports_bot: true
  add_optical_ports_arms: false
  bend:
    function: bend_euler
  combiner:
    function: mmi2x2
  cross_section: xs_sc
  cross_section_x_bot: null
  cross_section_x_top: null
  delta_length: 10.0
  extend_ports_straight_x: null
  length_x: 0.1
  length_y: 2.0
  mirror_bot: false
  nbends: 2
  port_e0_combiner: o4
  port_e0_splitter: o3
  port_e1_combiner: o3
  port_e1_splitter: o2
  splitter: mmi1x2
  straight:
    function: straight
  straight_x_bot: null
  straight_x_top: null
  straight_y: null
  with_splitter: true
