function: straight_heater_meander
info: {}
module: gdsfactory.components.straight_heater_meander
name: straight_heater_meander_f9764d28
settings:
  bend:
    function: bend_euler
  cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      add_pins_function_name: null
      radius: 10
      radius_min: 5
  extension_length: 15.0
  heater_taper_length: 10.0
  heater_width: 2.5
  layer_heater: null
  length: 1000.0
  n: 3
  port_orientation1: null
  port_orientation2: null
  post_process: null
  radius: null
  spacing: 2.0
  straight:
    function: straight
  straight_widths: null
  taper:
    function: taper_cross_section
    module: gdsfactory.components.taper_cross_section
    settings:
      linear: true
      npoints: 2
  taper_length: 10
  via_stack: via_stack_heater_mtop
