info: {}
name: ring_double_heater_gdsf_1cb4fda3
settings:
  bend: bend_euler
  coupler_ring: coupler_ring
  cross_section: strip
  cross_section_heater: heater_metal
  cross_section_waveguide_heater: strip_heater_metal
  gap: 0.2
  length_extension: 3
  length_x: 1
  length_y: 0.01
  radius: 10
  straight: straight
  via_stack: via_stack_heater_mtop_mini
  via_stack_offset:
  - 1
  - 0
  with_drop: true
