function_name: pad_gsg_short
info: {}
module: gdsfactory.components.pad_gsg
name: pad_gsg_short
ports: {}
settings:
  layer_metal: MTOP
  metal_spacing: 5.0
  pad:
    function: pad
  pad_spacing: 150
  short: true
  size:
  - 22
  - 7
  via_stack:
    function: rectangle
    settings:
      layer: MTOP
