name: cutback_bend
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - -250.0
    - 150.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  cols: 5
  component:
    function: bend_euler
  rows: 6
  straight:
    function: straight
  straight_length: 5.0
