info:
  length: 10.0
  route_info_length: 10.0
  route_info_strip_length: 10.0
  route_info_type: strip
  route_info_weight: 10.0
  width: 0.5
name: add_termination_Cstraig_311ba3e0
settings:
  component: straight
  terminator: Ftaper_Mgdsfactorypcomponentsptapersptaper_SW0p1
