info: {}
name: straight_heater_metal_s_61c5bdef
settings:
  cross_section_heater: heater_metal
  cross_section_waveguide_heater: strip_heater_metal
  heater_taper_length: 5
  length: 320
  via_stack: via_stack_heater_mtop
