info:
  period: 1.072
  polarization: tm
  wavelength: 1.53
name: grating_coupler_ellipti_a84a2f63
settings:
  cross_section: strip
  end_straight_length: 0.2
  fiber_angle: 15.0
  grating_line_width: 0.6
  layer_trench: SHALLOW_ETCH
  n_periods: 30
  ncladding: 1.443
  neff: 1.8
  p_start: 26
  polarization: tm
  taper: taper
  taper_angle: 30.0
  taper_length: 16.6
  trenches_extra_angle: 9.0
  wavelength: 1.53
