name: mzi_2e88f57c_rotate_564dd830
ports:
  o1:
    center:
    - 0.625
    - -10.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - -0.625
    - -10.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 270.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - -0.625
    - 117.12
    layer:
    - 1
    - 0
    name: o3
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 0.625
    - 117.12
    layer:
    - 1
    - 0
    name: o4
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 0.5
  top_l_e1:
    center:
    - -22.625
    - 19.5
    layer:
    - 49
    - 0
    name: top_l_e1
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e2:
    center:
    - -28.125
    - 25.0
    layer:
    - 49
    - 0
    name: top_l_e2
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e3:
    center:
    - -22.625
    - 30.5
    layer:
    - 49
    - 0
    name: top_l_e3
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_l_e4:
    center:
    - -17.125
    - 25.0
    layer:
    - 49
    - 0
    name: top_l_e4
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e1:
    center:
    - -22.625
    - 76.6
    layer:
    - 49
    - 0
    name: top_r_e1
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e2:
    center:
    - -28.125
    - 82.1
    layer:
    - 49
    - 0
    name: top_r_e2
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e3:
    center:
    - -22.625
    - 87.6
    layer:
    - 49
    - 0
    name: top_r_e3
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 11.0
  top_r_e4:
    center:
    - -17.125
    - 82.1
    layer:
    - 49
    - 0
    name: top_r_e4
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 11.0
settings:
  changed:
    component:
      component: mzi
      settings:
        combiner:
          function: mmi2x2
        port_e0_combiner: o4
        port_e0_splitter: o4
        port_e1_combiner: o3
        port_e1_splitter: o3
        splitter:
          function: mmi2x2
        straight_x_top: straight_heater_metal
  child:
    changed:
      combiner:
        function: mmi2x2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight_x_top: straight_heater_metal
    child: null
    default:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner: null
      cross_section: strip
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o3
      port_e0_splitter: o3
      port_e1_combiner: o2
      port_e1_splitter: o2
      splitter: mmi1x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: null
      straight_y: null
      with_splitter: true
    full:
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: strip
      cross_section_x_bot: null
      cross_section_x_top: null
      delta_length: 10.0
      length_x: 0.1
      length_y: 2.0
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_bot: null
      straight_x_top: straight_heater_metal
      straight_y: null
      with_splitter: true
    function_name: mzi
    info: {}
    info_version: 2
    module: gdsfactory.components.mzi
    name: mzi_2e88f57c
  default:
    angle: 90
    recenter: false
  full:
    angle: 90
    component:
      component: mzi
      settings:
        combiner:
          function: mmi2x2
        port_e0_combiner: o4
        port_e0_splitter: o4
        port_e1_combiner: o3
        port_e1_splitter: o3
        splitter:
          function: mmi2x2
        straight_x_top: straight_heater_metal
    recenter: false
  function_name: rotate
  info: {}
  info_version: 2
  module: gdsfactory.functions
  name: mzi_2e88f57c_rotate_564dd830
