info: {}
name: ring_crow_G0p2_0p2_0p2__3f923492
settings:
  bends:
  - bend_circular
  - bend_circular
  - bend_circular
  gaps:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  input_straight_cross_section: strip
  output_straight_cross_section: strip
  radius:
  - 10
  - 10
  - 10
  ring_cross_sections:
  - strip
  - strip
  - strip
