info: {}
name: straight_heater_doped_r_7951dce3
settings:
  cross_section: Fcross_section_Mgdsfactorypcross_section_SR10_RM5_Sslab
  cross_section_heater: rib_heater_doped
  heater_gap: 0.8
  heater_width: 2
  length: 320
  nsections: 3
  taper: taper_cross_section
  via_stack: Fvia_stack_Mgdsfactorypcomponentspvia_stack_SLSLAB90_NPP_M1_VNone_None_Fvia_Mgdsfactorypcomponentspvia_SLVIAC
  via_stack_gap: 0
  via_stack_metal: Fvia_stack_Mgdsfactorypcomponentspvia_stack_SLM1_M2_MTOP_VFvia_Mgdsfactorypcomponentspvia_SLVIA1_E2_Fvia_Mgdsfactorypcomponentspvia_SLVIA2_None
  via_stack_metal_size:
  - 10
  - 10
  via_stack_size:
  - 10
  - 10
  width: 0.5
  xoffset_tip1: 0.2
  xoffset_tip2: 0.4
