function: spiral_double
info:
  length: 635.0904965875375
module: gdsfactory.components.spiral_double
name: spiral_double
settings:
  bend:
    function: bend_circular
  cross_section: xs_sc
  npoints: 1000
  number_of_loops: 3
  separation: 2.0
