info:
  length: 10.186
  min_bend_radius: 11.857
name: coupler_G0p236_L20_D4_D_83b94450
settings:
  allow_min_radius_violation: false
  cross_section: strip
  dx: 10.0
  dy: 4.0
  gap: 0.236
  length: 20.0
