function: container
info: {}
module: gdsfactory.cell
name: mzi_container_da768e5d
settings:
  component:
    function: mzi
    module: gdsfactory.components.mzi
    settings:
      add_electrical_ports_bot: true
      add_optical_ports_arms: false
      bend:
        function: bend_euler
      combiner:
        function: mmi2x2
      cross_section: xs_sc
      delta_length: 10.0
      length_x: 100
      length_y: 2.0
      min_length: 0.01
      mirror_bot: false
      nbends: 2
      port_e0_combiner: o4
      port_e0_splitter: o4
      port_e1_combiner: o3
      port_e1_splitter: o3
      splitter:
        function: mmi2x2
      straight:
        function: straight
      straight_x_top: straight_heater_metal
      with_splitter: true
  function:
    function: add_padding
