info:
  xsize: 11
  ysize: 11
name: via_stack_S11_11_LSLAB9_a891ac05
settings:
  correct_size: true
  layers:
  - SLAB90
  - M1
  - M2
  - MTOP
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  size:
  - 11
  - 11
  slot_horizontal: false
  slot_vertical: false
  vias:
  - viac
  - via1
  - via2
  - null
