function: edge_coupler_array
info: {}
module: gdsfactory.components.edge_coupler_array
name: edge_coupler_array
settings:
  alignment_port: o1
  angle: 0
  bend:
    function: bend_euler
  edge_coupler:
    function: taper
    module: gdsfactory.components.taper
    settings:
      length: 100
      width2: 0.2
      with_two_ports: true
  n: 5
  pitch: 127.0
  place_x_by_port: true
  space_y_by_port: false
  text:
    function: text_rectangular
  text_mirror: false
  text_offset:
  - 10
  - 20
  text_rotation: 0
  x_reflection: false
