name: taper_abf5825d
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed:
    length: 100
    width2: 0.2
    with_two_ports: false
  child: null
  default:
    cross_section: strip
    length: 10.0
    port: null
    port_order_name:
    - o1
    - o2
    port_order_types:
    - optical
    - optical
    width1: 0.5
    width2: null
    with_bbox: true
    with_two_ports: true
  full:
    cross_section: strip
    length: 100
    port: null
    port_order_name:
    - o1
    - o2
    port_order_types:
    - optical
    - optical
    width1: 0.5
    width2: 0.2
    with_bbox: true
    with_two_ports: false
  function_name: taper
  info:
    length: 100
    width1: 0.5
    width2: 0.2
  info_version: 2
  module: gdsfactory.components.taper
  name: taper_abf5825d
