info: {}
name: pad_gsg_short_VSFrectan_52992fb5
settings:
  layer_metal: MTOP
  metal_spacing: 5
  pad: pad
  pad_spacing: 150
  route_xsize: 50
  short: false
  size:
  - 22
  - 7
  via_stack: Frectangle_Mgdsfactorypcomponentsprectangle_SLMTOP
