info:
  length: 10
  min_bend_radius: 10000
  route_info_length: 10
  route_info_strip_length: 10
  route_info_type: strip
  route_info_weight: 10
  width: 0.5
name: straight_gdsfactorypcom_f2286423
settings:
  cross_section: strip
  length: 10
  npoints: 2
