info:
  length: 670.4639999999999
name: spiral_racetrack_MR5_SL_dd5880dc
settings:
  allow_min_radius_violation: 1
  bend_factory: bend_euler
  bend_s_factory: bend_s
  cross_section: strip
  extra_90_deg_bend: 0
  min_radius: 5
  n_bend_points: 99
  spacings:
  - 2
  - 2
  - 3
  - 3
  - 2
  - 2
  straight_factory: straight
  straight_length: 20
  with_inner_ports: 0
