function: add_trenches
info:
  length: 10.186
  min_bend_radius: 11.857
module: gdsfactory.components.add_trenches
name: coupler_add_trenches
settings:
  bot: true
  component:
    function: coupler
  cross_section: xs_rc_with_trenches
  left: false
  right: false
  top: true
