function: snspd
info:
  area: 80
  num_squares: 750.0
  size:
  - 10
  - 8
module: gdsfactory.components.snspd
name: snspd
settings:
  layer:
  - 1
  - 0
  size:
  - 10
  - 8
  terminals_same_side: false
  turn_ratio: 4
  wire_pitch: 0.6
  wire_width: 0.2
