name: mmi1x2_with_sbend
ports:
  o1:
    center:
    - -0.25
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 13.25
    - 2.15
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 13.25
    - -2.15
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  cross_section: xs_sc
  s_bend:
    function: bend_s
  with_sbend: true
