function_name: loss_deembedding_ch12_34
info: {}
module: gdsfactory.components.grating_coupler_loss
name: loss_deembedding_ch12_34
ports: {}
settings:
  cross_section: xs_sc
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    module: gdsfactory.components.grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  pitch: 127.0
  port_name: o1
