function: add_fiducials_offsets
info:
  xsize: 100.0
  ysize: 100.0
module: gdsfactory.components.add_fiducials
name: add_fiducials_offsets
settings:
  component:
    function: pad_array
  fiducial: cross
  offsets:
    - - 0
      - 100
    - - 0
      - -100
