name: mmi2x2_with_sbend
ports:
  o1:
    center:
    - -12.0
    - -2.45
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - -12.0
    - 2.45
    layer:
    - 1
    - 0
    name: o2
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o3:
    center:
    - 20.0
    - 2.45
    layer:
    - 1
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o4:
    center:
    - 20.0
    - -2.45
    layer:
    - 1
    - 0
    name: o4
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  changed: {}
  child: null
  default:
    cross_section: strip
    s_bend:
      function: bend_s
    with_sbend: true
  full:
    cross_section: strip
    s_bend:
      function: bend_s
    with_sbend: true
  function_name: mmi2x2_with_sbend
  info: {}
  info_version: 2
  module: gdsfactory.components.mmi2x2_with_sbend
  name: mmi2x2_with_sbend
