info: {}
name: grating_coupler_loss_fi_40851e17
settings:
  cross_section: strip
  grating_coupler: Fgrating_coupler_elliptical_trenches_Mgdsfactorypcomponentspgrating_coupler_elliptical_trenches_SPte_TA35
  pitch: 127
  port_name: o1
  rotation: -90
