name: pad_gsg_short_shortFalse
ports: {}
settings:
  changed:
    short: false
  child: null
  default:
    layer_metal: M3
    metal_spacing: 5.0
    pad:
      function: pad
    pad_spacing: 150
    short: true
    size:
    - 22
    - 7
    via_stack:
      function: rectangle
      settings:
        layer: M3
  full:
    layer_metal: M3
    metal_spacing: 5.0
    pad:
      function: pad
    pad_spacing: 150
    short: false
    size:
    - 22
    - 7
    via_stack:
      function: rectangle
      settings:
        layer: M3
  function_name: pad_gsg_short
  info: {}
  info_version: 2
  module: gdsfactory.components.pad_gsg
  name: pad_gsg_short_shortFalse
