function: bend_euler
info:
  dy: 10.0
  length: 16.637
  radius: 10.0
  radius_min: 7.061
  route_info_length: 16.637
  route_info_n_bend_90: 1.0
  route_info_type: xs_sc
  route_info_weight: 16.637
  route_info_xs_sc_length: 16.637
  width: 0.5
module: gdsfactory.components.bend_euler
name: bend_euler
settings:
  add_bbox: null
  add_pins: true
  angle: 90.0
  cross_section: xs_sc
  direction: ccw
  layer: null
  npoints: null
  p: 0.5
  post_process: null
  radius: null
  width: null
  with_arc_floorplan: true
