name: straight_299ab026
ports:
  e1:
    center:
    - 0.0
    - 0.0
    layer:
    - 49
    - 0
    name: e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.0
  e2:
    center:
    - 10.0
    - 0.0
    layer:
    - 49
    - 0
    name: e2
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.0
settings:
  add_bbox: null
  add_pins: true
  cross_section: xs_metal_routing
  layer: null
  length: 10.0
  npoints: 2
  width: null
