info:
  length: 10
  route_info_length: 10
  route_info_metal_routing_length: 10
  route_info_type: metal_routing
  route_info_weight: 10
  width: 10
name: straight_L10_N2_CSmetal_routing
settings:
  cross_section: metal_routing
  length: 10
  npoints: 2
