name: ring_single
ports:
  o1:
    center:
    - -17.0
    - 0.0
    layer:
    - 1
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.5
  o2:
    center:
    - 13.0
    - 0.0
    layer:
    - 1
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.5
settings:
  bend:
    function: bend_euler
  bend_coupler:
    function: bend_euler
  coupler_ring:
    function: coupler_ring
  cross_section: xs_sc
  gap: 0.2
  length_x: 4.0
  length_y: 0.6
  pass_cross_section_to_bend: true
  radius: 10.0
  straight:
    function: straight
