info:
  period: 0.676
  polarization: te
  wavelength: 1.53
name: grating_coupler_ellipti_7b8aa449
settings:
  cross_section: strip
  end_straight_length: 0.2
  fiber_angle: 15
  grating_line_width: 0.343
  layer_trench: SHALLOW_ETCH
  n_periods: 30
  ncladding: 1.443
  neff: 2.638
  p_start: 26
  polarization: te
  taper: taper
  taper_angle: 35
  taper_length: 16.6
  trenches_extra_angle: 9
  wavelength: 1.53
