function: demo_cross_section_setting
info:
  length: 10.0
  route_info_length: 10.0
  route_info_type: strip
  route_info_weight: 10.0
  route_info_strip_length: 10.0
  width: 0.5
module: test_serialize
name: demo_cross_section_setting
settings:
  cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      radius: 10
      radius_min: 5
