name: verniers
ports: {}
settings:
  changed: {}
  child: null
  default:
    gap: 0.1
    layer_label: LABEL
    widths:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    xsize: 100
  full:
    gap: 0.1
    layer_label: LABEL
    widths:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    xsize: 100
  function_name: verniers
  info: {}
  info_version: 2
  module: gdsfactory.components.verniers
  name: verniers
