function: tapers
info:
  length: 20
  route_info_length: 20.0
  route_info_type: xs_ee3ca4da
  route_info_weight: 20.0
  route_info_xs_ee3ca4da_length: 20.0
  width: 2
module: test_add_fiber_array
name: tapers
settings: {}
