name: mmi1x2_6b2171cd
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 34
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.9
  o2:
    center:
    - 15.5
    - 0.625
    layer:
    - 34
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.9
  o3:
    center:
    - 15.5
    - -0.625
    layer:
    - 34
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.9
settings:
  changed:
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        name: strip
        width: 0.9
    width: 0.9
  child: null
  default:
    cross_section: strip
    gap_mmi: 0.25
    length_mmi: 5.5
    length_taper: 10.0
    taper:
      function: taper
    width: null
    width_mmi: 2.5
    width_taper: 1.0
    with_bbox: true
  full:
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        name: strip
        width: 0.9
    gap_mmi: 0.25
    length_mmi: 5.5
    length_taper: 10.0
    taper:
      function: taper
    width: 0.9
    width_mmi: 2.5
    width_taper: 1.0
    with_bbox: true
  function_name: mmi1x2
  info: {}
  info_version: 2
  module: gdsfactory.components.mmi1x2
  name: mmi1x2_6b2171cd
