name: mzi_3bf7917f
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 34
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.9
  o2:
    center:
    - 87.12
    - 0.0
    layer:
    - 34
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.9
settings:
  changed:
    bend:
      function: bend_euler
      settings:
        cross_section:
          add_pins_function_module: gdsfactory.samples.pdk.fab_c
          add_pins_function_name: add_pins
          auto_widen: false
          auto_widen_minimum_length: 200.0
          bbox_layers:
          - - 36
            - 0
          bbox_offsets:
          - 3.0
          components_along_path: []
          end_straight_length: 0.01
          gap: 3.0
          info: {}
          min_length: 0.01
          radius: 10.0
          radius_min: 5.0
          sections:
          - hidden: false
            insets: null
            layer:
            - 34
            - 0
            name: _default
            offset: 0.0
            offset_function: null
            port_names:
            - o1
            - o2
            port_types:
            - optical
            - optical
            simplify: null
            width: 0.9
            width_function: null
          start_straight_length: 0.01
          taper_length: 10.0
          width_wide: null
    cross_section:
      add_pins_function_module: gdsfactory.samples.pdk.fab_c
      add_pins_function_name: add_pins
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers:
      - - 36
        - 0
      bbox_offsets:
      - 3.0
      components_along_path: []
      end_straight_length: 0.01
      gap: 3.0
      info: {}
      min_length: 0.01
      radius: 10.0
      radius_min: 5.0
      sections:
      - hidden: false
        insets: null
        layer:
        - 34
        - 0
        name: _default
        offset: 0.0
        offset_function: null
        port_names:
        - o1
        - o2
        port_types:
        - optical
        - optical
        simplify: null
        width: 0.9
        width_function: null
      start_straight_length: 0.01
      taper_length: 10.0
      width_wide: null
    splitter:
      function: mmi1x2
      settings:
        cross_section:
          add_pins_function_module: gdsfactory.samples.pdk.fab_c
          add_pins_function_name: add_pins
          auto_widen: false
          auto_widen_minimum_length: 200.0
          bbox_layers:
          - - 36
            - 0
          bbox_offsets:
          - 3.0
          components_along_path: []
          end_straight_length: 0.01
          gap: 3.0
          info: {}
          min_length: 0.01
          radius: 10.0
          radius_min: 5.0
          sections:
          - hidden: false
            insets: null
            layer:
            - 34
            - 0
            name: _default
            offset: 0.0
            offset_function: null
            port_names:
            - o1
            - o2
            port_types:
            - optical
            - optical
            simplify: null
            width: 0.9
            width_function: null
          start_straight_length: 0.01
          taper_length: 10.0
          width_wide: null
        width: 0.9
    straight:
      function: straight
      settings:
        cross_section:
          add_pins_function_module: gdsfactory.samples.pdk.fab_c
          add_pins_function_name: add_pins
          auto_widen: false
          auto_widen_minimum_length: 200.0
          bbox_layers:
          - - 36
            - 0
          bbox_offsets:
          - 3.0
          components_along_path: []
          end_straight_length: 0.01
          gap: 3.0
          info: {}
          min_length: 0.01
          radius: 10.0
          radius_min: 5.0
          sections:
          - hidden: false
            insets: null
            layer:
            - 34
            - 0
            name: _default
            offset: 0.0
            offset_function: null
            port_names:
            - o1
            - o2
            port_types:
            - optical
            - optical
            simplify: null
            width: 0.9
            width_function: null
          start_straight_length: 0.01
          taper_length: 10.0
          width_wide: null
  child: null
  default:
    add_electrical_ports_bot: true
    add_optical_ports_arms: false
    bend:
      function: bend_euler
    combiner: null
    cross_section: xs_sc
    cross_section_x_bot: null
    cross_section_x_top: null
    delta_length: 10.0
    length_x: 0.1
    length_y: 2.0
    mirror_bot: false
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter: mmi1x2
    straight:
      function: straight
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  full:
    add_electrical_ports_bot: true
    add_optical_ports_arms: false
    bend:
      function: bend_euler
      settings:
        cross_section:
          add_pins_function_module: gdsfactory.samples.pdk.fab_c
          add_pins_function_name: add_pins
          auto_widen: false
          auto_widen_minimum_length: 200.0
          bbox_layers:
          - - 36
            - 0
          bbox_offsets:
          - 3.0
          components_along_path: []
          end_straight_length: 0.01
          gap: 3.0
          info: {}
          min_length: 0.01
          radius: 10.0
          radius_min: 5.0
          sections:
          - hidden: false
            insets: null
            layer:
            - 34
            - 0
            name: _default
            offset: 0.0
            offset_function: null
            port_names:
            - o1
            - o2
            port_types:
            - optical
            - optical
            simplify: null
            width: 0.9
            width_function: null
          start_straight_length: 0.01
          taper_length: 10.0
          width_wide: null
    combiner: null
    cross_section:
      add_pins_function_module: gdsfactory.samples.pdk.fab_c
      add_pins_function_name: add_pins
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers:
      - - 36
        - 0
      bbox_offsets:
      - 3.0
      components_along_path: []
      end_straight_length: 0.01
      gap: 3.0
      info: {}
      min_length: 0.01
      radius: 10.0
      radius_min: 5.0
      sections:
      - hidden: false
        insets: null
        layer:
        - 34
        - 0
        name: _default
        offset: 0.0
        offset_function: null
        port_names:
        - o1
        - o2
        port_types:
        - optical
        - optical
        simplify: null
        width: 0.9
        width_function: null
      start_straight_length: 0.01
      taper_length: 10.0
      width_wide: null
    cross_section_x_bot: null
    cross_section_x_top: null
    delta_length: 10.0
    length_x: 0.1
    length_y: 2.0
    mirror_bot: false
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter:
      function: mmi1x2
      settings:
        cross_section:
          add_pins_function_module: gdsfactory.samples.pdk.fab_c
          add_pins_function_name: add_pins
          auto_widen: false
          auto_widen_minimum_length: 200.0
          bbox_layers:
          - - 36
            - 0
          bbox_offsets:
          - 3.0
          components_along_path: []
          end_straight_length: 0.01
          gap: 3.0
          info: {}
          min_length: 0.01
          radius: 10.0
          radius_min: 5.0
          sections:
          - hidden: false
            insets: null
            layer:
            - 34
            - 0
            name: _default
            offset: 0.0
            offset_function: null
            port_names:
            - o1
            - o2
            port_types:
            - optical
            - optical
            simplify: null
            width: 0.9
            width_function: null
          start_straight_length: 0.01
          taper_length: 10.0
          width_wide: null
        width: 0.9
    straight:
      function: straight
      settings:
        cross_section:
          add_pins_function_module: gdsfactory.samples.pdk.fab_c
          add_pins_function_name: add_pins
          auto_widen: false
          auto_widen_minimum_length: 200.0
          bbox_layers:
          - - 36
            - 0
          bbox_offsets:
          - 3.0
          components_along_path: []
          end_straight_length: 0.01
          gap: 3.0
          info: {}
          min_length: 0.01
          radius: 10.0
          radius_min: 5.0
          sections:
          - hidden: false
            insets: null
            layer:
            - 34
            - 0
            name: _default
            offset: 0.0
            offset_function: null
            port_names:
            - o1
            - o2
            port_types:
            - optical
            - optical
            simplify: null
            width: 0.9
            width_function: null
          start_straight_length: 0.01
          taper_length: 10.0
          width_wide: null
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  function_name: mzi
  info: {}
  info_version: 2
  module: gdsfactory.components.mzi
  name: mzi_3bf7917f
