name: bend_euler_1da7fd5c
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 34
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 1.0
  o2:
    center:
    - 10.0
    - 10.0
    layer:
    - 34
    - 0
    name: o2
    orientation: 90.0
    port_type: optical
    shear_angle: null
    width: 1.0
settings:
  changed:
    cross_section:
      add_pins_function_module: gdsfactory.samples.pdk.fab_c
      add_pins_function_name: add_pins
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers:
      - - 36
        - 0
      bbox_offsets:
      - 3.0
      components_along_path: []
      end_straight_length: 0.01
      gap: 3.0
      info: {}
      min_length: 0.01
      radius: 10.0
      radius_min: 5.0
      sections:
      - hidden: false
        insets: null
        layer:
        - 34
        - 0
        name: _default
        offset: 0.0
        offset_function: null
        port_names:
        - o1
        - o2
        port_types:
        - optical
        - optical
        simplify: null
        width: 1.0
        width_function: null
      start_straight_length: 0.01
      taper_length: 10.0
      width_wide: null
  child: null
  default:
    add_bbox: null
    add_pins: true
    angle: 90.0
    cross_section: xs_sc
    direction: ccw
    layer: null
    npoints: null
    p: 0.5
    radius: null
    width: null
    with_arc_floorplan: true
  full:
    add_bbox: null
    add_pins: true
    angle: 90.0
    cross_section:
      add_pins_function_module: gdsfactory.samples.pdk.fab_c
      add_pins_function_name: add_pins
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers:
      - - 36
        - 0
      bbox_offsets:
      - 3.0
      components_along_path: []
      end_straight_length: 0.01
      gap: 3.0
      info: {}
      min_length: 0.01
      radius: 10.0
      radius_min: 5.0
      sections:
      - hidden: false
        insets: null
        layer:
        - 34
        - 0
        name: _default
        offset: 0.0
        offset_function: null
        port_names:
        - o1
        - o2
        port_types:
        - optical
        - optical
        simplify: null
        width: 1.0
        width_function: null
      start_straight_length: 0.01
      taper_length: 10.0
      width_wide: null
    direction: ccw
    layer: null
    npoints: null
    p: 0.5
    radius: null
    width: null
    with_arc_floorplan: true
  function_name: bend_euler
  info:
    dy: 10.0
    length: 16.637
    radius: 10.0
    radius_min: 7.061
    route_info:
      length: 16.637
      n_bend_90: 1.0
      type: xs_7c0f28d3
      weight: 16.637
      xs_7c0f28d3_length: 16.637
    width: 1.0
  info_version: 2
  module: gdsfactory.components.bend_euler
  name: bend_euler_1da7fd5c
