name: mmi1x2_974492f5
settings:
  changed:
    cross_section:
      function: strip
      settings:
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 0.9
    width: 0.9
  child: null
  default:
    cross_section: strip
    gap_mmi: 0.25
    length_mmi: 5.5
    length_taper: 10.0
    taper:
      function: taper
    width: null
    width_mmi: 2.5
    width_taper: 1.0
    with_bbox: true
  full:
    cross_section:
      function: strip
      settings:
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        width: 0.9
    gap_mmi: 0.25
    length_mmi: 5.5
    length_taper: 10.0
    taper:
      function: taper
    width: 0.9
    width_mmi: 2.5
    width_taper: 1.0
    with_bbox: true
  function_name: mmi1x2
  info: {}
  info_version: 2
  module: gdsfactory.components.mmi1x2
  name: mmi1x2_974492f5
