name: straight_df3841b1
ports:
  o1:
    center:
    - 0.0
    - 0.0
    layer:
    - 34
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 1.0
  o2:
    center:
    - 10.0
    - 0.0
    layer:
    - 34
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 1.0
settings:
  changed:
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        name: strip
        width: 1.0
  child: null
  default:
    cross_section: strip
    length: 10.0
    npoints: 2
    with_bbox: true
  full:
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        name: strip
        width: 1.0
    length: 10.0
    npoints: 2
    with_bbox: true
  function_name: straight
  info:
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        name: strip
        width: 1.0
    function_name: cross_section
    length: 10.0
    settings:
      add_bbox: null
      add_pins:
        function: add_pins
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers:
      - - 36
        - 0
      bbox_offsets:
      - 3
      cladding_layers: null
      cladding_offsets: null
      cladding_simplify: null
      decorator: null
      end_straight_length: 0.01
      gap: 3.0
      info: null
      layer:
      - 34
      - 0
      min_length: 0.01
      mirror: false
      name: strip
      offset: 0
      port_names:
      - o1
      - o2
      port_types:
      - optical
      - optical
      radius: 10.0
      sections: null
      snap_to_grid: null
      start_straight_length: 0.01
      taper_length: 10.0
      width: 1.0
      width_wide: null
    width: 1.0
  info_version: 2
  module: gdsfactory.components.straight
  name: straight_df3841b1
