function: bend_euler
info:
  dy: 10.0
  length: 16.637
  radius: 10.0
  radius_min: 7.061
  route_info_length: 16.637
  route_info_n_bend_90: 1.0
  route_info_type: xs_6dc110e2
  route_info_weight: 16.637
  route_info_xs_6dc110e2_length: 16.637
  width: 1.0
module: gdsfactory.components.bend_euler
name: bend_euler_a0a4eac7
settings:
  angle: 90.0
  cross_section:
    bbox_layers:
    - - 36
      - 0
    bbox_offsets:
    - 3.0
    components_along_path: []
    radius: 10.0
    radius_min: 5.0
    sections:
    - hidden: false
      insets: null
      layer:
      - 34
      - 0
      name: _default
      offset: 0.0
      offset_function: null
      port_names:
      - o1
      - o2
      port_types:
      - optical
      - optical
      simplify: null
      width: 1.0
      width_function: null
  direction: ccw
  info: null
  npoints: null
  p: 0.5
  post_process:
  - function: add_pins
    module: gdsfactory.add_pins
    settings:
      function:
        function: add_pin_rectangle_inside
        module: gdsfactory.add_pins
        settings:
          layer_label: null
          pin_length: 0.001
      pin_length: 0.5
  radius: null
  with_arc_floorplan: true
