name: mzi_64695ba0
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 34
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 0.9
  o2:
    center:
    - 81.12
    - 0.0
    layer:
    - 34
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 0.9
settings:
  changed:
    bend:
      function: bend_euler
      settings:
        cross_section:
          function: cross_section
          settings:
            add_bbox: null
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            name: strip
            width: 0.9
        with_bbox: true
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        name: strip
        width: 0.9
    splitter:
      function: mmi1x2
      settings:
        cross_section:
          function: cross_section
          settings:
            add_bbox: null
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            name: strip
            width: 0.9
        width: 0.9
    straight:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            add_bbox: null
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            name: strip
            width: 0.9
        with_bbox: true
  child: null
  default:
    add_optical_ports_arms: false
    bend:
      function: bend_euler
    combiner: null
    cross_section: strip
    cross_section_x_bot: null
    cross_section_x_top: null
    delta_length: 10.0
    length_x: 0.1
    length_y: 2.0
    mirror_bot: false
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter: mmi1x2
    straight:
      function: straight
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  full:
    add_optical_ports_arms: false
    bend:
      function: bend_euler
      settings:
        cross_section:
          function: cross_section
          settings:
            add_bbox: null
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            name: strip
            width: 0.9
        with_bbox: true
    combiner: null
    cross_section:
      function: cross_section
      settings:
        add_bbox: null
        add_pins:
          function: add_pins
        bbox_layers:
        - - 36
          - 0
        bbox_offsets:
        - 3
        layer:
        - 34
        - 0
        name: strip
        width: 0.9
    cross_section_x_bot: null
    cross_section_x_top: null
    delta_length: 10.0
    length_x: 0.1
    length_y: 2.0
    mirror_bot: false
    nbends: 2
    port_e0_combiner: o3
    port_e0_splitter: o3
    port_e1_combiner: o2
    port_e1_splitter: o2
    splitter:
      function: mmi1x2
      settings:
        cross_section:
          function: cross_section
          settings:
            add_bbox: null
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            name: strip
            width: 0.9
        width: 0.9
    straight:
      function: straight
      settings:
        cross_section:
          function: cross_section
          settings:
            add_bbox: null
            add_pins:
              function: add_pins
            bbox_layers:
            - - 36
              - 0
            bbox_offsets:
            - 3
            layer:
            - 34
            - 0
            name: strip
            width: 0.9
        with_bbox: true
    straight_x_bot: null
    straight_x_top: null
    straight_y: null
    with_splitter: true
  function_name: mzi
  info: {}
  info_version: 2
  module: gdsfactory.components.mzi
  name: mzi_64695ba0
