name: mmi1x2_44e6dc12
ports:
  o1:
    center:
    - -10.0
    - 0.0
    layer:
    - 34
    - 0
    name: o1
    orientation: 180.0
    port_type: optical
    shear_angle: null
    width: 1.0
  o2:
    center:
    - 15.5
    - 0.625
    layer:
    - 34
    - 0
    name: o2
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 1.0
  o3:
    center:
    - 15.5
    - -0.625
    layer:
    - 34
    - 0
    name: o3
    orientation: 0.0
    port_type: optical
    shear_angle: null
    width: 1.0
settings:
  changed:
    cross_section:
      add_pins_function_module: gdsfactory.samples.pdk.fab_c
      add_pins_function_name: add_pins
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers:
      - - 36
        - 0
      bbox_offsets:
      - 3.0
      components_along_path: []
      end_straight_length: 0.01
      gap: 3.0
      info: {}
      min_length: 0.01
      radius: 10.0
      radius_min: 5.0
      sections:
      - hidden: false
        insets: null
        layer:
        - 34
        - 0
        name: _default
        offset: 0.0
        offset_function: null
        port_names:
        - o1
        - o2
        port_types:
        - optical
        - optical
        simplify: null
        width: 1.0
        width_function: null
      start_straight_length: 0.01
      taper_length: 10.0
      width_wide: null
    width: 1.0
    width_mmi: 3
  child: null
  default:
    cross_section: xs_sc
    gap_mmi: 0.25
    length_mmi: 5.5
    length_taper: 10.0
    straight:
      function: straight
    taper:
      function: taper
    width: null
    width_mmi: 2.5
    width_taper: 1.0
    with_bbox: true
  full:
    cross_section:
      add_pins_function_module: gdsfactory.samples.pdk.fab_c
      add_pins_function_name: add_pins
      auto_widen: false
      auto_widen_minimum_length: 200.0
      bbox_layers:
      - - 36
        - 0
      bbox_offsets:
      - 3.0
      components_along_path: []
      end_straight_length: 0.01
      gap: 3.0
      info: {}
      min_length: 0.01
      radius: 10.0
      radius_min: 5.0
      sections:
      - hidden: false
        insets: null
        layer:
        - 34
        - 0
        name: _default
        offset: 0.0
        offset_function: null
        port_names:
        - o1
        - o2
        port_types:
        - optical
        - optical
        simplify: null
        width: 1.0
        width_function: null
      start_straight_length: 0.01
      taper_length: 10.0
      width_wide: null
    gap_mmi: 0.25
    length_mmi: 5.5
    length_taper: 10.0
    straight:
      function: straight
    taper:
      function: taper
    width: 1.0
    width_mmi: 3
    width_taper: 1.0
    with_bbox: true
  function_name: mmi1x2
  info: {}
  info_version: 2
  module: gdsfactory.components.mmi1x2
  name: mmi1x2_44e6dc12
