name: coupler_gap0p244_length_25400d4f
settings:
  changed:
    component:
      name: coupler_gap0p244_length5p67
      settings:
        changed:
          gap: 0.244
          length: 5.67
        child: null
        default:
          coupler_straight:
            function: coupler_straight
          coupler_symmetric:
            function: coupler_symmetric
          cross_section: strip
          dx: 10
          dy: 5
          gap: 0.236
          length: 20
        full:
          coupler_straight:
            function: coupler_straight
          coupler_symmetric:
            function: coupler_symmetric
          cross_section: strip
          dx: 10
          dy: 5
          gap: 0.244
          length: 5.67
        function_name: coupler
        info:
          length: 10.313
          min_bend_radius: 9.465
        info_version: 2
        module: gdsfactory.components.coupler
        name: coupler_gap0p244_length5p67
      version: 0.0.1
    optical_routing_type: 2
  child:
    changed:
      gap: 0.244
      length: 5.67
    child: null
    default:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section: strip
      dx: 10
      dy: 5
      gap: 0.236
      length: 20
    full:
      coupler_straight:
        function: coupler_straight
      coupler_symmetric:
        function: coupler_symmetric
      cross_section: strip
      dx: 10
      dy: 5
      gap: 0.244
      length: 5.67
    function_name: coupler
    info:
      length: 10.313
      min_bend_radius: 9.465
    info_version: 2
    module: gdsfactory.components.coupler
    name: coupler_gap0p244_length5p67
  default:
    component:
      function: straight
    component_name: null
    cross_section: strip
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label: TEXT
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  full:
    component:
      name: coupler_gap0p244_length5p67
      settings:
        changed:
          gap: 0.244
          length: 5.67
        child: null
        default:
          coupler_straight:
            function: coupler_straight
          coupler_symmetric:
            function: coupler_symmetric
          cross_section: strip
          dx: 10
          dy: 5
          gap: 0.236
          length: 20
        full:
          coupler_straight:
            function: coupler_straight
          coupler_symmetric:
            function: coupler_symmetric
          cross_section: strip
          dx: 10
          dy: 5
          gap: 0.244
          length: 5.67
        function_name: coupler
        info:
          length: 10.313
          min_bend_radius: 9.465
        info_version: 2
        module: gdsfactory.components.coupler
        name: coupler_gap0p244_length5p67
      version: 0.0.1
    component_name: null
    cross_section: strip
    gc_port_labels: null
    gc_port_name: o1
    get_input_labels_function:
      function: get_input_labels
    grating_coupler:
      function: grating_coupler_elliptical_trenches
      settings:
        polarization: te
        taper_angle: 35
    layer_label: TEXT
    optical_routing_type: 2
    select_ports:
      function: select_ports
      settings:
        port_type: optical
  function_name: add_fiber_array
  info: {}
  info_version: 2
  module: gdsfactory.routing.add_fiber_array
  name: coupler_gap0p244_length_25400d4f
version: 0.0.1
