---
name: Build binder Notebook Container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files in repo
        uses: actions/checkout@master

      - name: update jupyter dependencies with repo2docker
        uses: machine-learning-apps/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          MYBINDERORG_TAG: ${{ github.event.pull_request.head.ref }}
