name: Codecov

on:
  push:
    branches:
      - masterjobs:
  build:
    name: Run rspec to generate code coverage
    runs-on: ubuntu-lateststeps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x- name: Run test cases
      run: |
        bundle exec rspec
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
